<definitions name="USIPolicyV2"
	targetNamespace="http://services.apmoller.net/USI/policy/v2.0"
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	>

    <wsdl:documentation>Shared WS policy file that is imported by all services implementing default, message-level, USI security</wsdl:documentation> 
    <xsd:annotation>
        <xsd:appinfo>
            <Metadata xmlns="http://services.apmoller.net/AMM/v2/meta">
                <Creator/>
                <Version>1.0.0</Version>
                <LastUpdateDate>14/07/2011</LastUpdateDate>
            </Metadata>
        </xsd:appinfo>
    </xsd:annotation>


	<!-- Policy Authentication definition -->
	<wsp:Policy wsu:Id="wss_username_token_service_policy">
		<sp:SupportingTokens
			xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
			<wsp:Policy xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy">
				<sp:UsernameToken
					sp:IncludeToken="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy/IncludeToken/AlwaysToRecipient">
					<wsp:Policy>
						<sp:WssUsernameToken10 />
					</wsp:Policy>
				</sp:UsernameToken>
			</wsp:Policy>
		</sp:SupportingTokens>
	</wsp:Policy>

</definitions>
