select B.NAME as name ,C.NAME as geoFenceType  from C_GDA_DFND_AREA A
INNER JOIN C_GDA_DFND_PMTR B ON B.GDA_DFND_AREA_ROWID=A.ROWID_OBJECT AND B.HUB_STATE_IND=1
INNER JOIN C_TYP_TYPE C ON C.CODE=B.PMTR_TYP_CD AND C.HUB_STATE_IND=1
where A.HUB_STATE_IND=1 AND A.ROWID_OBJECT=?