/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.facility.smds.operations.MSK;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Facility Address */
@org.apache.avro.specific.AvroGenerated
public class address extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4745821652443348554L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"address\",\"namespace\":\"com.maersk.facility.smds.operations.MSK\",\"doc\":\"Facility Address\",\"fields\":[{\"name\":\"houseNumber\",\"type\":[\"null\",\"string\"]},{\"name\":\"street\",\"type\":[\"null\",\"string\"]},{\"name\":\"city\",\"type\":[\"null\",\"string\"]},{\"name\":\"postalCode\",\"type\":[\"null\",\"string\"]},{\"name\":\"poBox\",\"type\":[\"null\",\"string\"]},{\"name\":\"district\",\"type\":[\"null\",\"string\"]},{\"name\":\"territory\",\"type\":[\"null\",\"string\"]},{\"name\":\"countryName\",\"type\":[\"null\",\"string\"]},{\"name\":\"countryCode\",\"type\":[\"null\",\"string\"]},{\"name\":\"addressLine2\",\"type\":[\"null\",\"string\"]},{\"name\":\"addressLine3\",\"type\":[\"null\",\"string\"]},{\"name\":\"latitude\",\"type\":[\"null\",\"string\"]},{\"name\":\"longitude\",\"type\":[\"null\",\"string\"]},{\"name\":\"addressQualityCheckIndicator\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<address> ENCODER =
      new BinaryMessageEncoder<address>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<address> DECODER =
      new BinaryMessageDecoder<address>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<address> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<address> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<address>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this address to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a address from a ByteBuffer. */
  public static address fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence houseNumber;
  @Deprecated public java.lang.CharSequence street;
  @Deprecated public java.lang.CharSequence city;
  @Deprecated public java.lang.CharSequence postalCode;
  @Deprecated public java.lang.CharSequence poBox;
  @Deprecated public java.lang.CharSequence district;
  @Deprecated public java.lang.CharSequence territory;
  @Deprecated public java.lang.CharSequence countryName;
  @Deprecated public java.lang.CharSequence countryCode;
  @Deprecated public java.lang.CharSequence addressLine2;
  @Deprecated public java.lang.CharSequence addressLine3;
  @Deprecated public java.lang.CharSequence latitude;
  @Deprecated public java.lang.CharSequence longitude;
  @Deprecated public java.lang.CharSequence addressQualityCheckIndicator;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public address() {}

  /**
   * All-args constructor.
   * @param houseNumber The new value for houseNumber
   * @param street The new value for street
   * @param city The new value for city
   * @param postalCode The new value for postalCode
   * @param poBox The new value for poBox
   * @param district The new value for district
   * @param territory The new value for territory
   * @param countryName The new value for countryName
   * @param countryCode The new value for countryCode
   * @param addressLine2 The new value for addressLine2
   * @param addressLine3 The new value for addressLine3
   * @param latitude The new value for latitude
   * @param longitude The new value for longitude
   * @param addressQualityCheckIndicator The new value for addressQualityCheckIndicator
   */
  public address(java.lang.CharSequence houseNumber, java.lang.CharSequence street, java.lang.CharSequence city, java.lang.CharSequence postalCode, java.lang.CharSequence poBox, java.lang.CharSequence district, java.lang.CharSequence territory, java.lang.CharSequence countryName, java.lang.CharSequence countryCode, java.lang.CharSequence addressLine2, java.lang.CharSequence addressLine3, java.lang.CharSequence latitude, java.lang.CharSequence longitude, java.lang.CharSequence addressQualityCheckIndicator) {
    this.houseNumber = houseNumber;
    this.street = street;
    this.city = city;
    this.postalCode = postalCode;
    this.poBox = poBox;
    this.district = district;
    this.territory = territory;
    this.countryName = countryName;
    this.countryCode = countryCode;
    this.addressLine2 = addressLine2;
    this.addressLine3 = addressLine3;
    this.latitude = latitude;
    this.longitude = longitude;
    this.addressQualityCheckIndicator = addressQualityCheckIndicator;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return houseNumber;
    case 1: return street;
    case 2: return city;
    case 3: return postalCode;
    case 4: return poBox;
    case 5: return district;
    case 6: return territory;
    case 7: return countryName;
    case 8: return countryCode;
    case 9: return addressLine2;
    case 10: return addressLine3;
    case 11: return latitude;
    case 12: return longitude;
    case 13: return addressQualityCheckIndicator;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: houseNumber = (java.lang.CharSequence)value$; break;
    case 1: street = (java.lang.CharSequence)value$; break;
    case 2: city = (java.lang.CharSequence)value$; break;
    case 3: postalCode = (java.lang.CharSequence)value$; break;
    case 4: poBox = (java.lang.CharSequence)value$; break;
    case 5: district = (java.lang.CharSequence)value$; break;
    case 6: territory = (java.lang.CharSequence)value$; break;
    case 7: countryName = (java.lang.CharSequence)value$; break;
    case 8: countryCode = (java.lang.CharSequence)value$; break;
    case 9: addressLine2 = (java.lang.CharSequence)value$; break;
    case 10: addressLine3 = (java.lang.CharSequence)value$; break;
    case 11: latitude = (java.lang.CharSequence)value$; break;
    case 12: longitude = (java.lang.CharSequence)value$; break;
    case 13: addressQualityCheckIndicator = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'houseNumber' field.
   * @return The value of the 'houseNumber' field.
   */
  public java.lang.CharSequence getHouseNumber() {
    return houseNumber;
  }

  /**
   * Sets the value of the 'houseNumber' field.
   * @param value the value to set.
   */
  public void setHouseNumber(java.lang.CharSequence value) {
    this.houseNumber = value;
  }

  /**
   * Gets the value of the 'street' field.
   * @return The value of the 'street' field.
   */
  public java.lang.CharSequence getStreet() {
    return street;
  }

  /**
   * Sets the value of the 'street' field.
   * @param value the value to set.
   */
  public void setStreet(java.lang.CharSequence value) {
    this.street = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }

  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'postalCode' field.
   * @return The value of the 'postalCode' field.
   */
  public java.lang.CharSequence getPostalCode() {
    return postalCode;
  }

  /**
   * Sets the value of the 'postalCode' field.
   * @param value the value to set.
   */
  public void setPostalCode(java.lang.CharSequence value) {
    this.postalCode = value;
  }

  /**
   * Gets the value of the 'poBox' field.
   * @return The value of the 'poBox' field.
   */
  public java.lang.CharSequence getPoBox() {
    return poBox;
  }

  /**
   * Sets the value of the 'poBox' field.
   * @param value the value to set.
   */
  public void setPoBox(java.lang.CharSequence value) {
    this.poBox = value;
  }

  /**
   * Gets the value of the 'district' field.
   * @return The value of the 'district' field.
   */
  public java.lang.CharSequence getDistrict() {
    return district;
  }

  /**
   * Sets the value of the 'district' field.
   * @param value the value to set.
   */
  public void setDistrict(java.lang.CharSequence value) {
    this.district = value;
  }

  /**
   * Gets the value of the 'territory' field.
   * @return The value of the 'territory' field.
   */
  public java.lang.CharSequence getTerritory() {
    return territory;
  }

  /**
   * Sets the value of the 'territory' field.
   * @param value the value to set.
   */
  public void setTerritory(java.lang.CharSequence value) {
    this.territory = value;
  }

  /**
   * Gets the value of the 'countryName' field.
   * @return The value of the 'countryName' field.
   */
  public java.lang.CharSequence getCountryName() {
    return countryName;
  }

  /**
   * Sets the value of the 'countryName' field.
   * @param value the value to set.
   */
  public void setCountryName(java.lang.CharSequence value) {
    this.countryName = value;
  }

  /**
   * Gets the value of the 'countryCode' field.
   * @return The value of the 'countryCode' field.
   */
  public java.lang.CharSequence getCountryCode() {
    return countryCode;
  }

  /**
   * Sets the value of the 'countryCode' field.
   * @param value the value to set.
   */
  public void setCountryCode(java.lang.CharSequence value) {
    this.countryCode = value;
  }

  /**
   * Gets the value of the 'addressLine2' field.
   * @return The value of the 'addressLine2' field.
   */
  public java.lang.CharSequence getAddressLine2() {
    return addressLine2;
  }

  /**
   * Sets the value of the 'addressLine2' field.
   * @param value the value to set.
   */
  public void setAddressLine2(java.lang.CharSequence value) {
    this.addressLine2 = value;
  }

  /**
   * Gets the value of the 'addressLine3' field.
   * @return The value of the 'addressLine3' field.
   */
  public java.lang.CharSequence getAddressLine3() {
    return addressLine3;
  }

  /**
   * Sets the value of the 'addressLine3' field.
   * @param value the value to set.
   */
  public void setAddressLine3(java.lang.CharSequence value) {
    this.addressLine3 = value;
  }

  /**
   * Gets the value of the 'latitude' field.
   * @return The value of the 'latitude' field.
   */
  public java.lang.CharSequence getLatitude() {
    return latitude;
  }

  /**
   * Sets the value of the 'latitude' field.
   * @param value the value to set.
   */
  public void setLatitude(java.lang.CharSequence value) {
    this.latitude = value;
  }

  /**
   * Gets the value of the 'longitude' field.
   * @return The value of the 'longitude' field.
   */
  public java.lang.CharSequence getLongitude() {
    return longitude;
  }

  /**
   * Sets the value of the 'longitude' field.
   * @param value the value to set.
   */
  public void setLongitude(java.lang.CharSequence value) {
    this.longitude = value;
  }

  /**
   * Gets the value of the 'addressQualityCheckIndicator' field.
   * @return The value of the 'addressQualityCheckIndicator' field.
   */
  public java.lang.CharSequence getAddressQualityCheckIndicator() {
    return addressQualityCheckIndicator;
  }

  /**
   * Sets the value of the 'addressQualityCheckIndicator' field.
   * @param value the value to set.
   */
  public void setAddressQualityCheckIndicator(java.lang.CharSequence value) {
    this.addressQualityCheckIndicator = value;
  }

  /**
   * Creates a new address RecordBuilder.
   * @return A new address RecordBuilder
   */
  public static com.maersk.facility.smds.operations.MSK.address.Builder newBuilder() {
    return new com.maersk.facility.smds.operations.MSK.address.Builder();
  }

  /**
   * Creates a new address RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new address RecordBuilder
   */
  public static com.maersk.facility.smds.operations.MSK.address.Builder newBuilder(com.maersk.facility.smds.operations.MSK.address.Builder other) {
    return new com.maersk.facility.smds.operations.MSK.address.Builder(other);
  }

  /**
   * Creates a new address RecordBuilder by copying an existing address instance.
   * @param other The existing instance to copy.
   * @return A new address RecordBuilder
   */
  public static com.maersk.facility.smds.operations.MSK.address.Builder newBuilder(com.maersk.facility.smds.operations.MSK.address other) {
    return new com.maersk.facility.smds.operations.MSK.address.Builder(other);
  }

  /**
   * RecordBuilder for address instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<address>
    implements org.apache.avro.data.RecordBuilder<address> {

    private java.lang.CharSequence houseNumber;
    private java.lang.CharSequence street;
    private java.lang.CharSequence city;
    private java.lang.CharSequence postalCode;
    private java.lang.CharSequence poBox;
    private java.lang.CharSequence district;
    private java.lang.CharSequence territory;
    private java.lang.CharSequence countryName;
    private java.lang.CharSequence countryCode;
    private java.lang.CharSequence addressLine2;
    private java.lang.CharSequence addressLine3;
    private java.lang.CharSequence latitude;
    private java.lang.CharSequence longitude;
    private java.lang.CharSequence addressQualityCheckIndicator;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.facility.smds.operations.MSK.address.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.houseNumber)) {
        this.houseNumber = data().deepCopy(fields()[0].schema(), other.houseNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.street)) {
        this.street = data().deepCopy(fields()[1].schema(), other.street);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.city)) {
        this.city = data().deepCopy(fields()[2].schema(), other.city);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[3].schema(), other.postalCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.poBox)) {
        this.poBox = data().deepCopy(fields()[4].schema(), other.poBox);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.district)) {
        this.district = data().deepCopy(fields()[5].schema(), other.district);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.territory)) {
        this.territory = data().deepCopy(fields()[6].schema(), other.territory);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.countryName)) {
        this.countryName = data().deepCopy(fields()[7].schema(), other.countryName);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.countryCode)) {
        this.countryCode = data().deepCopy(fields()[8].schema(), other.countryCode);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.addressLine2)) {
        this.addressLine2 = data().deepCopy(fields()[9].schema(), other.addressLine2);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.addressLine3)) {
        this.addressLine3 = data().deepCopy(fields()[10].schema(), other.addressLine3);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.latitude)) {
        this.latitude = data().deepCopy(fields()[11].schema(), other.latitude);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.longitude)) {
        this.longitude = data().deepCopy(fields()[12].schema(), other.longitude);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.addressQualityCheckIndicator)) {
        this.addressQualityCheckIndicator = data().deepCopy(fields()[13].schema(), other.addressQualityCheckIndicator);
        fieldSetFlags()[13] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing address instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.facility.smds.operations.MSK.address other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.houseNumber)) {
        this.houseNumber = data().deepCopy(fields()[0].schema(), other.houseNumber);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.street)) {
        this.street = data().deepCopy(fields()[1].schema(), other.street);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.city)) {
        this.city = data().deepCopy(fields()[2].schema(), other.city);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.postalCode)) {
        this.postalCode = data().deepCopy(fields()[3].schema(), other.postalCode);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.poBox)) {
        this.poBox = data().deepCopy(fields()[4].schema(), other.poBox);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.district)) {
        this.district = data().deepCopy(fields()[5].schema(), other.district);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.territory)) {
        this.territory = data().deepCopy(fields()[6].schema(), other.territory);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.countryName)) {
        this.countryName = data().deepCopy(fields()[7].schema(), other.countryName);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.countryCode)) {
        this.countryCode = data().deepCopy(fields()[8].schema(), other.countryCode);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.addressLine2)) {
        this.addressLine2 = data().deepCopy(fields()[9].schema(), other.addressLine2);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.addressLine3)) {
        this.addressLine3 = data().deepCopy(fields()[10].schema(), other.addressLine3);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.latitude)) {
        this.latitude = data().deepCopy(fields()[11].schema(), other.latitude);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.longitude)) {
        this.longitude = data().deepCopy(fields()[12].schema(), other.longitude);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.addressQualityCheckIndicator)) {
        this.addressQualityCheckIndicator = data().deepCopy(fields()[13].schema(), other.addressQualityCheckIndicator);
        fieldSetFlags()[13] = true;
      }
    }

    /**
      * Gets the value of the 'houseNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getHouseNumber() {
      return houseNumber;
    }

    /**
      * Sets the value of the 'houseNumber' field.
      * @param value The value of 'houseNumber'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setHouseNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.houseNumber = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'houseNumber' field has been set.
      * @return True if the 'houseNumber' field has been set, false otherwise.
      */
    public boolean hasHouseNumber() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'houseNumber' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearHouseNumber() {
      houseNumber = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'street' field.
      * @return The value.
      */
    public java.lang.CharSequence getStreet() {
      return street;
    }

    /**
      * Sets the value of the 'street' field.
      * @param value The value of 'street'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setStreet(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.street = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'street' field has been set.
      * @return True if the 'street' field has been set, false otherwise.
      */
    public boolean hasStreet() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'street' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearStreet() {
      street = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }

    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.city = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearCity() {
      city = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'postalCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getPostalCode() {
      return postalCode;
    }

    /**
      * Sets the value of the 'postalCode' field.
      * @param value The value of 'postalCode'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setPostalCode(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.postalCode = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'postalCode' field has been set.
      * @return True if the 'postalCode' field has been set, false otherwise.
      */
    public boolean hasPostalCode() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'postalCode' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearPostalCode() {
      postalCode = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'poBox' field.
      * @return The value.
      */
    public java.lang.CharSequence getPoBox() {
      return poBox;
    }

    /**
      * Sets the value of the 'poBox' field.
      * @param value The value of 'poBox'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setPoBox(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.poBox = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'poBox' field has been set.
      * @return True if the 'poBox' field has been set, false otherwise.
      */
    public boolean hasPoBox() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'poBox' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearPoBox() {
      poBox = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'district' field.
      * @return The value.
      */
    public java.lang.CharSequence getDistrict() {
      return district;
    }

    /**
      * Sets the value of the 'district' field.
      * @param value The value of 'district'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setDistrict(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.district = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'district' field has been set.
      * @return True if the 'district' field has been set, false otherwise.
      */
    public boolean hasDistrict() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'district' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearDistrict() {
      district = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'territory' field.
      * @return The value.
      */
    public java.lang.CharSequence getTerritory() {
      return territory;
    }

    /**
      * Sets the value of the 'territory' field.
      * @param value The value of 'territory'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setTerritory(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.territory = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'territory' field has been set.
      * @return True if the 'territory' field has been set, false otherwise.
      */
    public boolean hasTerritory() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'territory' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearTerritory() {
      territory = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'countryName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountryName() {
      return countryName;
    }

    /**
      * Sets the value of the 'countryName' field.
      * @param value The value of 'countryName'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setCountryName(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.countryName = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'countryName' field has been set.
      * @return True if the 'countryName' field has been set, false otherwise.
      */
    public boolean hasCountryName() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'countryName' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearCountryName() {
      countryName = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'countryCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountryCode() {
      return countryCode;
    }

    /**
      * Sets the value of the 'countryCode' field.
      * @param value The value of 'countryCode'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setCountryCode(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.countryCode = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'countryCode' field has been set.
      * @return True if the 'countryCode' field has been set, false otherwise.
      */
    public boolean hasCountryCode() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'countryCode' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearCountryCode() {
      countryCode = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'addressLine2' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressLine2() {
      return addressLine2;
    }

    /**
      * Sets the value of the 'addressLine2' field.
      * @param value The value of 'addressLine2'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setAddressLine2(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.addressLine2 = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'addressLine2' field has been set.
      * @return True if the 'addressLine2' field has been set, false otherwise.
      */
    public boolean hasAddressLine2() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'addressLine2' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearAddressLine2() {
      addressLine2 = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'addressLine3' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressLine3() {
      return addressLine3;
    }

    /**
      * Sets the value of the 'addressLine3' field.
      * @param value The value of 'addressLine3'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setAddressLine3(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.addressLine3 = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'addressLine3' field has been set.
      * @return True if the 'addressLine3' field has been set, false otherwise.
      */
    public boolean hasAddressLine3() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'addressLine3' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearAddressLine3() {
      addressLine3 = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'latitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLatitude() {
      return latitude;
    }

    /**
      * Sets the value of the 'latitude' field.
      * @param value The value of 'latitude'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setLatitude(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.latitude = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'latitude' field has been set.
      * @return True if the 'latitude' field has been set, false otherwise.
      */
    public boolean hasLatitude() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'latitude' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearLatitude() {
      latitude = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'longitude' field.
      * @return The value.
      */
    public java.lang.CharSequence getLongitude() {
      return longitude;
    }

    /**
      * Sets the value of the 'longitude' field.
      * @param value The value of 'longitude'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setLongitude(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.longitude = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'longitude' field has been set.
      * @return True if the 'longitude' field has been set, false otherwise.
      */
    public boolean hasLongitude() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'longitude' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearLongitude() {
      longitude = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'addressQualityCheckIndicator' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddressQualityCheckIndicator() {
      return addressQualityCheckIndicator;
    }

    /**
      * Sets the value of the 'addressQualityCheckIndicator' field.
      * @param value The value of 'addressQualityCheckIndicator'.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder setAddressQualityCheckIndicator(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.addressQualityCheckIndicator = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'addressQualityCheckIndicator' field has been set.
      * @return True if the 'addressQualityCheckIndicator' field has been set, false otherwise.
      */
    public boolean hasAddressQualityCheckIndicator() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'addressQualityCheckIndicator' field.
      * @return This builder.
      */
    public com.maersk.facility.smds.operations.MSK.address.Builder clearAddressQualityCheckIndicator() {
      addressQualityCheckIndicator = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public address build() {
      try {
        address record = new address();
        record.houseNumber = fieldSetFlags()[0] ? this.houseNumber : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.street = fieldSetFlags()[1] ? this.street : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.city = fieldSetFlags()[2] ? this.city : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.postalCode = fieldSetFlags()[3] ? this.postalCode : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.poBox = fieldSetFlags()[4] ? this.poBox : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.district = fieldSetFlags()[5] ? this.district : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.territory = fieldSetFlags()[6] ? this.territory : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.countryName = fieldSetFlags()[7] ? this.countryName : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.countryCode = fieldSetFlags()[8] ? this.countryCode : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.addressLine2 = fieldSetFlags()[9] ? this.addressLine2 : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.addressLine3 = fieldSetFlags()[10] ? this.addressLine3 : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.latitude = fieldSetFlags()[11] ? this.latitude : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.longitude = fieldSetFlags()[12] ? this.longitude : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.addressQualityCheckIndicator = fieldSetFlags()[13] ? this.addressQualityCheckIndicator : (java.lang.CharSequence) defaultValue(fields()[13]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<address>
    WRITER$ = (org.apache.avro.io.DatumWriter<address>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<address>
    READER$ = (org.apache.avro.io.DatumReader<address>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
