select E.NAME as name ,F.NAME as fenceType  from
    C_FCT_ALT_CODES A
        INNER JOIN C_TYP_TYPE B ON B.ROWID_OBJECT=A.TYP_TYPE_ROWID AND B.HUB_STATE_IND=1 and B.CODE ='ALT_CODE.GEOID'
        INNER JOIN C_ALT_CODE C ON C.CODE=A.CODE AND C.HUB_STATE_IND=1
        INNER JOIN C_GDA_DFND_AREA D ON D.ROWID_OBJECT=C.GDA_DFND_AREA_ROWID AND D.HUB_STATE_IND=1 and TYP_TYPE_CD ='GDA.SITE'
        INNER JOIN C_GDA_DFND_PMTR E ON E.GDA_DFND_AREA_ROWID=D.ROWID_OBJECT AND E.HUB_STATE_IND=1
        INNER JOIN C_TYP_TYPE F ON F.CODE=E.PMTR_TYP_CD AND F.HUB_STATE_IND=1
where A.HUB_STATE_IND=1 AND A.FCT_ROWID=?