select C.NAME as codeType,
       B.CODE as code
from C_GDA_DFND_AREA A
         INNER JOIN C_ALT_CODE B ON B.GDA_DFND_AREA_ROWID = A.ROWID_OBJECT AND B.HUB_STATE_IND = 1
         INNER JOIN C_TYP_TYPE C ON C.ROWID_OBJECT = B.TYP_TYPE_ROWID AND C.HUB_STATE_IND = 1
where A.HUB_STATE_IND = 1
  AND A.ROWID_OBJECT=?