select B.CITY_ROWID as parentRowID,
       C.NAME as name,
       D.NAME as type
from C_FCT_ADDR_REL A
         INNER JOIN C_CTM_PSTL_ADDR B ON B.ROWID_OBJECT = A.ADDR_ROWID AND A.HUB_STATE_IND = 1
         INNER JOIN C_GDA_DFND_AREA C ON C.ROWID_OBJECT = B.CITY_ROWID AND C.HUB_STATE_IND = 1
         INNER JOIN  C_TYP_TYPE D ON  D.CODE =C.TYP_TYPE_CD AND D.HUB_STATE_IND = 1
where A.HUB_STATE_IND ='1' and A.FCT_ROWID=?