/**
 *
 */
package net.apmoller.services.cmd.searchfacility.dao;

// TODO: Auto-generated Javadoc
/**
 * The Interface DaoConstants.
 *
 * @author SBA399
 */
public interface DaoConstants {

	/** The record limit string. */
	String RECORD_LIMIT_STRING = "record.limit";

	/** The sip properties file name. */
	String SIP_PROPERTIES_FILE_NAME = "/environment.properties";

	String BUSINESS_PROPERTIES_FILE_NAME = "/business_en_US.properties";

	/** The file name separator. */
	String FILE_NAME_SEPARATOR = "_";

	/** The datasounce name. */
	String DATASOURCE_NAME = "SMDS_FCT_DATASOURCE";

	/** The properties file extension. */
	String PROPERTIES_FILE_EXTENSION = ".properties";

	/** The inputmap country. */
	/* Constants for input map */
	String INPUTMAP_COUNTRY = "country";

	/** The inputmap country code. */
	String INPUTMAP_COUNTRY_CODE = "countrycode";
	String INPUTMAP_COUNTRY_GEOID = "countrygeoid";
	String INPUTMAP_REGION_GEOID = "regiongeoid";
	String INPUTMAP_CITY_GEOID = "citygeoid";
	/** The inputmap city. */
	String INPUTMAP_CITY = "city";

	/** The inputmap facility name. */
	String INPUTMAP_FACILITY_NAME = "facilityname";

	/** The inputmap facility name. */
	String INPUTMAP_FACILITY_CATEGORY = "facilitycategory";

	/** The inputmap trading name. */
	String INPUTMAP_FACILITY_TYPE = "facilitytype";

	/** The inputmap lify cycle status. */
	String INPUTMAP_LIFY_CYCLE_STATUS = "lifecyclestatus";

	/** The inputmap house no. */
	String INPUTMAP_HOUSE_NO = "houseno";

	/** The inputmap street name. */
	String INPUTMAP_STREET_NAME = "streetname";

	/** The inputmap street name. */
	String INPUTMAP_OFFER_CODES = "offercode";

	/** The inputmap region. */
	String INPUTMAP_REGION = "region";

	/** The inputmap postal code. */
	String INPUTMAP_POSTAL_CODE = "postalcode";

	/** The inputmap latitude. */
	String INPUTMAP_LATITUDE = "latitude";

	/** The inputmap longitude type. */
	String INPUTMAP_LONGITUDE= "longitude";

	/** The inputmap latitude. */
	String INPUTMAP_FCT_GEO_ID = "geoid";

	/** The inputmap longitude type. */
	String INPUTMAP_FCT_RKST_CODE= "rkstcode";

	/** The inputmap facilityLifecycleStatus . */
	String INPUTMAP_FACILITY_LIFECYCLESTATUS = "facilityLifecycleStatus";

	/** The customer status active. */
	String FACILITY_STATUS_ACTIVE = "ACTIVE";

	/** The customer status inactive. */
	String FACILITY_STATUS_INACTIVE = "INACTIVE";

	/** The customer status suspended. */
	String FACILITY_STATUS_SUSPENDED = "SUSPENDED";

	/** The customer status active char. */
	String FACILITY_STATUS_ACTIVE_CHAR = "A";

	/** The customer status inactive char. */
	String FACILITY_STATUS_INACTIVE_CHAR = "I";

	/** The customer status suspended char. */
	String FACILITY_STATUS_SUSPENDED_CHAR = "S";

	/** The search customer wildcard character. */
	String SEARCH_FACILITY_WILDCARD_CHARACTER = "\\*";

	/** The search customer sql wildcard character. */
	String SEARCH_FACILITY_SQL_WILDCARD_CHARACTER = "%";

	/** The search customer resultset column country. */
	String SEARCH_FACILITY_RESULTSET_COLUMN_COUNTRY = "COUNTRY_NAME";

	/** The search customer resultset column country code. */
	String SEARCH_FACILITY_RESULTSET_COLUMN_COUNTRY_CODE = "COUNTRY_CODE";




	String SEARCH_FACILITY_RESULTSET_COLUMN_COUNTRY_GEOID = "COUNTRY_GEOID";
	String SEARCH_FACILITY_RESULTSET_COLUMN_CITY_GEOID = "CITY_GEOID";
	String SEARCH_FACILITY_RESULTSET_COLUMN_REGION_GEOID = "REGION_GEOID";

	/** The search customer resultset column city. */
	String SEARCH_FACILITY_RESULTSET_COLUMN_CITY = "CITY";

	/** The search customer resultset column customer code. */
	String SEARCH_FACILITY_RESULTSET_COLUMN_NAME = "FACILITY_NAME";

	/** The search customer resultset column legalname. */
	String SEARCH_FACILITY_RESULTSET_COLUMN_CATEGORY = "FCT_CATEGORY";

	/** The search customer resultset column legalname. */
	String SEARCH_FACILITY_RESULTSET_COLUMN_TYPE = "FCT_OPS_TYPE_CD";

	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_COLUMN_HOUSE_NO= "HOUSE_NUM";
	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_COLUMN_STREET_NAME= "STREET";
	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_COLUMN_REGION= "REGION_NAME";

	String SEARCH_FACILITY_RESULTSET_COLUMN_REGION_CODE="REGION_CODE";

	String SEARCH_FACILITY_RESULTSET_COLUMN_REGION_ISO_CODE="REGION_ISO_CODE";

	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_COLUMN_POSTAL_CODE= "POST_CODE";


	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_COLUMN_OFFER_CODE= "FCT_OFFERING_CD";

	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_COLUMN_LATITUDE= "LAT_GEOSPATIAL";

	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_COLUMN_LONGITUDE= "LNG_GEOSPATIAL";

	String SEARCH_FACILITY_RESULTSET_COLUMN_COMM_FCT_TYPE_CD= "COMM_FCT_TYPE_CD";
	String SEARCH_FACILITY_RESULTSET_COLUMN_COMM_FCT_BRAND_CD= "COMM_FCT_BRAND_CD";
	String SEARCH_FACILITY_RESULTSET_COLUMN_COMM_FCT_FUNC_CD= "COMM_FCT_FUNC_CD";


	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_FCT_STATUS= "FACILITY_STATUS";

	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_FCT_OFFERING_NM= "FCT_OFFERING_NM";
	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_FCT_GEO_ID= "FCT_ALT_CODE_TYP_CD";

	/** The search facility resultset column . */
	String SEARCH_FACILITY_RESULTSET_FCT_RKST_ID= "FCT_ALT_CODE";

	/** below are the retrieval constants used. */
	String RETRIEVE_FACILITY_RESULTSET_FCT_ID= "FCT_MDM_ID";
	String RETRIEVE_FACILITY_RESULTSET_MDM_ID= "FACILITY_MDM_ID";
	String RETRIEVE_FACILITY_RESULTSET_FCT_ALT_CODE= "FCT_ALT_CODE";
	String RETRIEVE_FACILITY_RESULTSET_ALT_CODE_TYPE_CD= "ALT_CODE_TYPE_CD";
	String RETRIEVE_FACILITY_RESULTSET_FCT_NAME="FCT_NAME";
	String RETRIEVE_FACILITY_RESULTSET_FCT_CATEGORY="FCT_CATEGORY";
	String RETRIEVE_FACILITY_RESULTSET_FCT_OPS_TYPE_CD="FCT_OPS_TYPE_CD";
	String RETRIEVE_FACILITY_RESULTSET_FCT_OPS_TYPE_ST="FCT_OPS_TYPE_START_DT";
	String RETRIEVE_FACILITY_RESULTSET_FCT_OPS_TYPE_END="FCT_OPS_TYPE_END_DT";


	String RETRIEVE_FACILITY_RESULTSET_TRNSP_START_DT="TRNSP_START_DT";
	String RETRIEVE_FACILITY_RESULTSET_FCT_TRNSP_END_DT="FCT_TRNSP_END_DT";
	String RETRIEVE_FACILITY_RESULTSET_FCT_OFFERING_END_DT="FCT_OFFERING_END_DT";
	String RETRIEVE_FACILITY_RESULTSET_FCT_OFFERING_START_DT="FCT_OFFERING_START_DT";


	String RETRIEVE_FACILITY_RESULTSET_FCT_STATUS="FCT_STATUS";
	String RETRIEVE_FACILITY_RESULTSET_FCT_URL="FCT_URL";
	String RETRIEVE_FACILITY_RESULTSET_FCT_DODAAC="DODAAC";
	String RETRIEVE_FACILITY_RESULTSET_WEIGHT_LMT_CRANE="WEIGHT_LMT_CRANE";
	String RETRIEVE_FACILITY_RESULTSET_VESSEL_OPO="VESSEL_OPO";
	String RETRIEVE_FACILITY_RESULTSET_WEIGHT_LMT_YARD="WEIGHT_LMT_YARD";
	String RETRIEVE_FACILITY_RESULTSET_FCT_WORKING_DAYS="FCT_WORKING_DAYS";
	String RETRIEVE_FACILITY_RESULTSET_FCT_DAY_OPEN="FCT_DAY_OPEN";
	String RETRIEVE_FACILITY_RESULTSET_FCT_DAY_CLOSE="FCT_DAY_CLOSE";
	String RETRIEVE_FACILITY_RESULTSET_FCT_TRANSPORT_CD="FCT_TRANSPORT_CD";
	String RETRIEVE_FACILITY_RESULTSET_EXT_EXPOSED_FLAG="EXT_EXPOSED_FLAG";
	String RETRIEVE_FACILITY_RESULTSET_EXT_OWNED_FLAG="EXT_OWNED_FLAG";
	String RETRIEVE_FACILITY_RESULTSET_VESSEL_AGENT="VESSEL_AGENT";
	String RETRIEVE_FACILITY_RESULTSET_OCE_FRGHT_PR="OCE_FRGHT_PR";
	String RETRIEVE_FACILITY_RESULTSET_HOUSE_NUM="HOUSE_NUM";
	String RETRIEVE_FACILITY_RESULTSET_STREET="STREET";
	String RETRIEVE_FACILITY_RESULTSET_BUILDING_NUM="BUILDING_NUM";
	String RETRIEVE_FACILITY_RESULTSET_SUBURB="SUBURB";
	String RETRIEVE_FACILITY_RESULTSET_DISTRICT="DISTRICT";
	String RETRIEVE_FACILITY_RESULTSET_CITY="CITY";
	String RETRIEVE_FACILITY_RESULTSET_REGION_NAME="REGION_NAME";
	String RETRIEVE_FACILITY_RESULTSET_ISO_REGION_CODE="ISO_REGION_CODE";
	String RETRIEVE_FACILITY_RESULTSET_ISO_COUNTRY_CODE="ISO_COUNTRY_CODE";
	String RETRIEVE_FACILITY_RESULTSET_POSTAL_CODE="POSTAL_CODE";
	String RETRIEVE_FACILITY_RESULTSET_GRP_CD="GRP_CD";
	String RETRIEVE_FACILITY_RESULTSET_FCT_OFFERING_CD="FCT_OFFERING_CD";
	String RETRIEVE_FACILITY_RESULTSET_FCT_OFFERING_NAME="FCT_OFFERING_NAME";
	String RETRIEVE_FACILITY_RESULTSET_GPS_FLAG="GPS_FLAG";
	String RETRIEVE_FACILITY_RESULTSET_GSM_FLAG="GSM_FLAG";
	String RETRIEVE_FACILITY_RESULTSET_FCT_DELETED_DT="FCT_DELETED_DT";
	String RETRIEVE_FACILITY_RESULTSET_COUNTRY_GEOID="COUNTRY_GEOID";
	String RETRIEVE_FACILITY_RESULTSET_CITY_GEOID="CITY_GEOID";
	String RETRIEVE_FACILITY_RESULTSET_REGION_GEOID="REGION_GEOID";
	String RETRIEVE_FACILITY_RESULTSET_LAT_GEOSPTL="LAT_GEOSPTL";
	String RETRIEVE_FACILITY_RESULTSET_LNG_GEOSPTL="LNG_GEOSPTL";
	String RETRIEVE_FACILITY_RESULTSET_ADDR_MDM_ID="ADDR_MDM_ID";
	String RETRIEVE_FACILITY_RESULTSET_FCT_ADDR_VALID_FROM_DT="FCT_ADDR_VALID_FROM_DT";
	String RETRIEVE_FACILITY_RESULTSET_FCT_ADDR_VALID_THRU_DT="FCT_ADDR_VALID_THRU_DT";
	String RETRIEVE_FACILITY_RESULTSET_ADDR_LAST_UPDATE_DT="ADDR_LAST_UPDATE_DT";
	String RETRIEVE_FACILITY_RESULTSET_ADDR_UPDATED_BY="ADDR_UPDATED_BY";
	String RETRIEVE_FACILITY_RESULTSET_ADDR_CREATE_DT="ADDR_CREATE_DT";
	String RETRIEVE_FACILITY_RESULTSET_ADDR_CREATOR="ADDR_CREATOR";


	String RETRIEVE_FACILITY_RESULTSET_FCT_LAST_UPDATE_DT="FCT_LAST_UPDATE_DT";
	String RETRIEVE_FACILITY_RESULTSET_FCT_UPDATED_BY="FCT_LAST_UPDATED_BY";
	String RETRIEVE_FACILITY_RESULTSET_FCT_CREATE_DT="FCT_CREATE_DT";
	String RETRIEVE_FACILITY_RESULTSET_FCT_CREATOR="FCT_CREATOR";

	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_FCT_TYPE_CD="COMM_FCT_TYPE_CD";
	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_FCT_BRAND_CD="COMM_FCT_BRAND_CD";
	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_FCT_BRAND_NM="COMM_FCT_BRAND_NM";
	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_FCT_FUNC_CD="COMM_FCT_FUNC_CD";
	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_FCT_FUNC_NM="COMM_FCT_FUNC_NM";
	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_FCT_DIALING_CD="COMM_FCT_DIALING_CD";
	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_FCT_DAILNG_CD_DESC="COMM_FCT_DAILNG_CD_DESC";
	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_TELECOM_NUM="TELECOM_NUM";
	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_IMP_MAIL="IMP_MAIL";
	String RETRIEVE_FACILITY_RESULTSET_FCT_COMM_EXP_MAIL="EXP_MAIL";





}
