//
//This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
//See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
//Any modifications to this file will be lost upon recompilation of the source schema. 
//Generated on: 2021.05.19 at 04:36:01 PM IST 
//


package com.maersk.mdm.taskdata.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
* This object contains factory methods for each 
* Java content interface and Java element interface 
* generated in the TestLearingPkg package. 
* <p>An ObjectFactory allows you to programatically 
* construct new instances of the Java representation 
* for XML content. The Java representation of XML 
* content can consist of schema derived interfaces 
* and classes representing the binding of schema 
* type definitions, element declarations and model 
* groups.  Factory methods for each of these are 
* provided in this class.
* 
*/
@XmlRegistry
public class ObjectFactory {


 /**
  * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: TestLearingPkg
  * 
  */
 public ObjectFactory() {
 }

 /**
  * Create an instance of {@link Geography }
  * 
  */
 public Geography createGeography() {
     return new Geography();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea }
  * 
  */
 public Geography.BusinessDefinedArea createGeographyBusinessDefinedArea() {
     return new Geography.BusinessDefinedArea();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea.Locations }
  * 
  */
 public Geography.BusinessDefinedArea.Locations createGeographyBusinessDefinedAreaLocations() {
     return new Geography.BusinessDefinedArea.Locations();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea.Locations.Location }
  * 
  */
 public Geography.BusinessDefinedArea.Locations.Location createGeographyBusinessDefinedAreaLocationsLocation() {
     return new Geography.BusinessDefinedArea.Locations.Location();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea.Locations.Location.AlternateCodes }
  * 
  */
 public Geography.BusinessDefinedArea.Locations.Location.AlternateCodes createGeographyBusinessDefinedAreaLocationsLocationAlternateCodes() {
     return new Geography.BusinessDefinedArea.Locations.Location.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea.ParentBDA }
  * 
  */
 public Geography.BusinessDefinedArea.ParentBDA createGeographyBusinessDefinedAreaParentBDA() {
     return new Geography.BusinessDefinedArea.ParentBDA();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea.ParentBDA.AlternateCodes }
  * 
  */
 public Geography.BusinessDefinedArea.ParentBDA.AlternateCodes createGeographyBusinessDefinedAreaParentBDAAlternateCodes() {
     return new Geography.BusinessDefinedArea.ParentBDA.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea.AlternateCodes }
  * 
  */
 public Geography.BusinessDefinedArea.AlternateCodes createGeographyBusinessDefinedAreaAlternateCodes() {
     return new Geography.BusinessDefinedArea.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.PostalCode }
  * 
  */
 public Geography.PostalCode createGeographyPostalCode() {
     return new Geography.PostalCode();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.BDA }
  * 
  */
 public Geography.PostalCode.BDA createGeographyPostalCodeBDA() {
     return new Geography.PostalCode.BDA();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.BDA.BDAType }
  * 
  */
 public Geography.PostalCode.BDA.BDAType createGeographyPostalCodeBDABDAType() {
     return new Geography.PostalCode.BDA.BDAType();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.BDA.BDAType.AlternateCodes }
  * 
  */
 public Geography.PostalCode.BDA.BDAType.AlternateCodes createGeographyPostalCodeBDABDATypeAlternateCodes() {
     return new Geography.PostalCode.BDA.BDAType.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.Parent }
  * 
  */
 public Geography.PostalCode.Parent createGeographyPostalCodeParent() {
     return new Geography.PostalCode.Parent();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.Parent.AlternateCodes }
  * 
  */
 public Geography.PostalCode.Parent.AlternateCodes createGeographyPostalCodeParentAlternateCodes() {
     return new Geography.PostalCode.Parent.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.Country }
  * 
  */
 public Geography.PostalCode.Country createGeographyPostalCodeCountry() {
     return new Geography.PostalCode.Country();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.Country.AlternateCodes }
  * 
  */
 public Geography.PostalCode.Country.AlternateCodes createGeographyPostalCodeCountryAlternateCodes() {
     return new Geography.PostalCode.Country.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.AlternateCodes }
  * 
  */
 public Geography.PostalCode.AlternateCodes createGeographyPostalCodeAlternateCodes() {
     return new Geography.PostalCode.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.Site }
  * 
  */
 public Geography.Site createGeographySite() {
     return new Geography.Site();
 }

 /**
  * Create an instance of {@link Geography.Site.BDA }
  * 
  */
 public Geography.Site.BDA createGeographySiteBDA() {
     return new Geography.Site.BDA();
 }

 /**
  * Create an instance of {@link Geography.Site.BDA.BDAType }
  * 
  */
 public Geography.Site.BDA.BDAType createGeographySiteBDABDAType() {
     return new Geography.Site.BDA.BDAType();
 }

 /**
  * Create an instance of {@link Geography.Site.BDA.BDAType.AlternateCodes }
  * 
  */
 public Geography.Site.BDA.BDAType.AlternateCodes createGeographySiteBDABDATypeAlternateCodes() {
     return new Geography.Site.BDA.BDAType.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.Site.Parent }
  * 
  */
 public Geography.Site.Parent createGeographySiteParent() {
     return new Geography.Site.Parent();
 }

 /**
  * Create an instance of {@link Geography.Site.Parent.AlternateCodes }
  * 
  */
 public Geography.Site.Parent.AlternateCodes createGeographySiteParentAlternateCodes() {
     return new Geography.Site.Parent.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.Site.Country }
  * 
  */
 public Geography.Site.Country createGeographySiteCountry() {
     return new Geography.Site.Country();
 }

 /**
  * Create an instance of {@link Geography.Site.Country.AlternateCodes }
  * 
  */
 public Geography.Site.Country.AlternateCodes createGeographySiteCountryAlternateCodes() {
     return new Geography.Site.Country.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.Site.GeoFence }
  * 
  */
 public Geography.Site.GeoFence createGeographySiteGeoFence() {
     return new Geography.Site.GeoFence();
 }

 /**
  * Create an instance of {@link Geography.Site.AlternateCodes }
  * 
  */
 public Geography.Site.AlternateCodes createGeographySiteAlternateCodes() {
     return new Geography.Site.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.Site.AlternateNames }
  * 
  */
 public Geography.Site.AlternateNames createGeographySiteAlternateNames() {
     return new Geography.Site.AlternateNames();
 }

 /**
  * Create an instance of {@link Geography.City }
  * 
  */
 public Geography.City createGeographyCity() {
     return new Geography.City();
 }

 /**
  * Create an instance of {@link Geography.City.BDA }
  * 
  */
 public Geography.City.BDA createGeographyCityBDA() {
     return new Geography.City.BDA();
 }

 /**
  * Create an instance of {@link Geography.City.BDA.BDAType }
  * 
  */
 public Geography.City.BDA.BDAType createGeographyCityBDABDAType() {
     return new Geography.City.BDA.BDAType();
 }

 /**
  * Create an instance of {@link Geography.City.BDA.BDAType.AlternateCodes }
  * 
  */
 public Geography.City.BDA.BDAType.AlternateCodes createGeographyCityBDABDATypeAlternateCodes() {
     return new Geography.City.BDA.BDAType.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.City.SubCityParent }
  * 
  */
 public Geography.City.SubCityParent createGeographyCitySubCityParent() {
     return new Geography.City.SubCityParent();
 }

 /**
  * Create an instance of {@link Geography.City.SubCityParent.AlternateCodes }
  * 
  */
 public Geography.City.SubCityParent.AlternateCodes createGeographyCitySubCityParentAlternateCodes() {
     return new Geography.City.SubCityParent.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.City.Parent }
  * 
  */
 public Geography.City.Parent createGeographyCityParent() {
     return new Geography.City.Parent();
 }

 /**
  * Create an instance of {@link Geography.City.Parent.AlternateCodes }
  * 
  */
 public Geography.City.Parent.AlternateCodes createGeographyCityParentAlternateCodes() {
     return new Geography.City.Parent.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.City.Country }
  * 
  */
 public Geography.City.Country createGeographyCityCountry() {
     return new Geography.City.Country();
 }

 /**
  * Create an instance of {@link Geography.City.Country.AlternateCodes }
  * 
  */
 public Geography.City.Country.AlternateCodes createGeographyCityCountryAlternateCodes() {
     return new Geography.City.Country.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.City.AlternateCodes }
  * 
  */
 public Geography.City.AlternateCodes createGeographyCityAlternateCodes() {
     return new Geography.City.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.City.AlternateNames }
  * 
  */
 public Geography.City.AlternateNames createGeographyCityAlternateNames() {
     return new Geography.City.AlternateNames();
 }

 /**
  * Create an instance of {@link Geography.StateProvince }
  * 
  */
 public Geography.StateProvince createGeographyStateProvince() {
     return new Geography.StateProvince();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.BDA }
  * 
  */
 public Geography.StateProvince.BDA createGeographyStateProvinceBDA() {
     return new Geography.StateProvince.BDA();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.BDA.BDAType }
  * 
  */
 public Geography.StateProvince.BDA.BDAType createGeographyStateProvinceBDABDAType() {
     return new Geography.StateProvince.BDA.BDAType();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.BDA.BDAType.AlternateCodes }
  * 
  */
 public Geography.StateProvince.BDA.BDAType.AlternateCodes createGeographyStateProvinceBDABDATypeAlternateCodes() {
     return new Geography.StateProvince.BDA.BDAType.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.Parent }
  * 
  */
 public Geography.StateProvince.Parent createGeographyStateProvinceParent() {
     return new Geography.StateProvince.Parent();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.Parent.AlternateCodes }
  * 
  */
 public Geography.StateProvince.Parent.AlternateCodes createGeographyStateProvinceParentAlternateCodes() {
     return new Geography.StateProvince.Parent.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.AlternateCodes }
  * 
  */
 public Geography.StateProvince.AlternateCodes createGeographyStateProvinceAlternateCodes() {
     return new Geography.StateProvince.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.AlternateNames }
  * 
  */
 public Geography.StateProvince.AlternateNames createGeographyStateProvinceAlternateNames() {
     return new Geography.StateProvince.AlternateNames();
 }

 /**
  * Create an instance of {@link Geography.Country }
  * 
  */
 public Geography.Country createGeographyCountry() {
     return new Geography.Country();
 }

 /**
  * Create an instance of {@link Geography.Country.BDA }
  * 
  */
 public Geography.Country.BDA createGeographyCountryBDA() {
     return new Geography.Country.BDA();
 }

 /**
  * Create an instance of {@link Geography.Country.BDA.BDAType }
  * 
  */
 public Geography.Country.BDA.BDAType createGeographyCountryBDABDAType() {
     return new Geography.Country.BDA.BDAType();
 }

 /**
  * Create an instance of {@link Geography.Country.BDA.BDAType.AlternateCodes }
  * 
  */
 public Geography.Country.BDA.BDAType.AlternateCodes createGeographyCountryBDABDATypeAlternateCodes() {
     return new Geography.Country.BDA.BDAType.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.Country.Parent }
  * 
  */
 public Geography.Country.Parent createGeographyCountryParent() {
     return new Geography.Country.Parent();
 }

 /**
  * Create an instance of {@link Geography.Country.Parent.AlternateCodes }
  * 
  */
 public Geography.Country.Parent.AlternateCodes createGeographyCountryParentAlternateCodes() {
     return new Geography.Country.Parent.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.Country.AlternateCodes }
  * 
  */
 public Geography.Country.AlternateCodes createGeographyCountryAlternateCodes() {
     return new Geography.Country.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.Country.AlternateNames }
  * 
  */
 public Geography.Country.AlternateNames createGeographyCountryAlternateNames() {
     return new Geography.Country.AlternateNames();
 }

 /**
  * Create an instance of {@link Geography.Continent }
  * 
  */
 public Geography.Continent createGeographyContinent() {
     return new Geography.Continent();
 }

 /**
  * Create an instance of {@link Geography.Continent.AlternateCodes }
  * 
  */
 public Geography.Continent.AlternateCodes createGeographyContinentAlternateCodes() {
     return new Geography.Continent.AlternateCodes();
 }

 /**
  * Create an instance of {@link Geography.Continent.AlternateNames }
  * 
  */
 public Geography.Continent.AlternateNames createGeographyContinentAlternateNames() {
     return new Geography.Continent.AlternateNames();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea.Locations.Location.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.BusinessDefinedArea.Locations.Location.AlternateCodes.AlternateCode createGeographyBusinessDefinedAreaLocationsLocationAlternateCodesAlternateCode() {
     return new Geography.BusinessDefinedArea.Locations.Location.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea.ParentBDA.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.BusinessDefinedArea.ParentBDA.AlternateCodes.AlternateCode createGeographyBusinessDefinedAreaParentBDAAlternateCodesAlternateCode() {
     return new Geography.BusinessDefinedArea.ParentBDA.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.BusinessDefinedArea.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.BusinessDefinedArea.AlternateCodes.AlternateCode createGeographyBusinessDefinedAreaAlternateCodesAlternateCode() {
     return new Geography.BusinessDefinedArea.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.BDA.BDAType.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.PostalCode.BDA.BDAType.AlternateCodes.AlternateCode createGeographyPostalCodeBDABDATypeAlternateCodesAlternateCode() {
     return new Geography.PostalCode.BDA.BDAType.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.Parent.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.PostalCode.Parent.AlternateCodes.AlternateCode createGeographyPostalCodeParentAlternateCodesAlternateCode() {
     return new Geography.PostalCode.Parent.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.Country.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.PostalCode.Country.AlternateCodes.AlternateCode createGeographyPostalCodeCountryAlternateCodesAlternateCode() {
     return new Geography.PostalCode.Country.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.PostalCode.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.PostalCode.AlternateCodes.AlternateCode createGeographyPostalCodeAlternateCodesAlternateCode() {
     return new Geography.PostalCode.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.Site.BDA.BDAType.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.Site.BDA.BDAType.AlternateCodes.AlternateCode createGeographySiteBDABDATypeAlternateCodesAlternateCode() {
     return new Geography.Site.BDA.BDAType.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.Site.Parent.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.Site.Parent.AlternateCodes.AlternateCode createGeographySiteParentAlternateCodesAlternateCode() {
     return new Geography.Site.Parent.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.Site.Country.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.Site.Country.AlternateCodes.AlternateCode createGeographySiteCountryAlternateCodesAlternateCode() {
     return new Geography.Site.Country.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.Site.GeoFence.GeoFenceTypes }
  * 
  */
 public Geography.Site.GeoFence.GeoFenceTypes createGeographySiteGeoFenceGeoFenceTypes() {
     return new Geography.Site.GeoFence.GeoFenceTypes();
 }

 /**
  * Create an instance of {@link Geography.Site.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.Site.AlternateCodes.AlternateCode createGeographySiteAlternateCodesAlternateCode() {
     return new Geography.Site.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.Site.AlternateNames.AlternateName }
  * 
  */
 public Geography.Site.AlternateNames.AlternateName createGeographySiteAlternateNamesAlternateName() {
     return new Geography.Site.AlternateNames.AlternateName();
 }

 /**
  * Create an instance of {@link Geography.City.BDA.BDAType.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.City.BDA.BDAType.AlternateCodes.AlternateCode createGeographyCityBDABDATypeAlternateCodesAlternateCode() {
     return new Geography.City.BDA.BDAType.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.City.SubCityParent.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.City.SubCityParent.AlternateCodes.AlternateCode createGeographyCitySubCityParentAlternateCodesAlternateCode() {
     return new Geography.City.SubCityParent.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.City.Parent.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.City.Parent.AlternateCodes.AlternateCode createGeographyCityParentAlternateCodesAlternateCode() {
     return new Geography.City.Parent.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.City.Country.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.City.Country.AlternateCodes.AlternateCode createGeographyCityCountryAlternateCodesAlternateCode() {
     return new Geography.City.Country.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.City.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.City.AlternateCodes.AlternateCode createGeographyCityAlternateCodesAlternateCode() {
     return new Geography.City.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.City.AlternateNames.AlternateName }
  * 
  */
 public Geography.City.AlternateNames.AlternateName createGeographyCityAlternateNamesAlternateName() {
     return new Geography.City.AlternateNames.AlternateName();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.BDA.BDAType.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.StateProvince.BDA.BDAType.AlternateCodes.AlternateCode createGeographyStateProvinceBDABDATypeAlternateCodesAlternateCode() {
     return new Geography.StateProvince.BDA.BDAType.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.Parent.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.StateProvince.Parent.AlternateCodes.AlternateCode createGeographyStateProvinceParentAlternateCodesAlternateCode() {
     return new Geography.StateProvince.Parent.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.StateProvince.AlternateCodes.AlternateCode createGeographyStateProvinceAlternateCodesAlternateCode() {
     return new Geography.StateProvince.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.StateProvince.AlternateNames.AlternateName }
  * 
  */
 public Geography.StateProvince.AlternateNames.AlternateName createGeographyStateProvinceAlternateNamesAlternateName() {
     return new Geography.StateProvince.AlternateNames.AlternateName();
 }

 /**
  * Create an instance of {@link Geography.Country.BDA.BDAType.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.Country.BDA.BDAType.AlternateCodes.AlternateCode createGeographyCountryBDABDATypeAlternateCodesAlternateCode() {
     return new Geography.Country.BDA.BDAType.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.Country.Parent.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.Country.Parent.AlternateCodes.AlternateCode createGeographyCountryParentAlternateCodesAlternateCode() {
     return new Geography.Country.Parent.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.Country.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.Country.AlternateCodes.AlternateCode createGeographyCountryAlternateCodesAlternateCode() {
     return new Geography.Country.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.Country.AlternateNames.AlternateName }
  * 
  */
 public Geography.Country.AlternateNames.AlternateName createGeographyCountryAlternateNamesAlternateName() {
     return new Geography.Country.AlternateNames.AlternateName();
 }

 /**
  * Create an instance of {@link Geography.Continent.AlternateCodes.AlternateCode }
  * 
  */
 public Geography.Continent.AlternateCodes.AlternateCode createGeographyContinentAlternateCodesAlternateCode() {
     return new Geography.Continent.AlternateCodes.AlternateCode();
 }

 /**
  * Create an instance of {@link Geography.Continent.AlternateNames.AlternateName }
  * 
  */
 public Geography.Continent.AlternateNames.AlternateName createGeographyContinentAlternateNamesAlternateName() {
     return new Geography.Continent.AlternateNames.AlternateName();
 }

}

