<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://services.apmoller.net/cmd/definitions/v2"
	xmlns:schema="http://services.apmoller.net/cmd/schemas"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://services.apmoller.net/cmd/definitions/v2"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">


	<wsdl:import location="./SearchCustomerService_Abstract.wsdl" namespace="http://services.apmoller.net/cmd/definitions/v2"/>

	<wsdl:binding name="SearchCustomerBinding"
		type="tns:SearchCustomer">

		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="searchCustomer">

			<soap:operation
				soapAction="http://services.apmoller.net/cmd/definitions/v2/searchCustomer" />
			<wsdl:input>



				<soap:body use="literal" />
				<soap:header use="literal" message="tns:searchCustomerHeader"
					part="header" />
			</wsdl:input>
			<wsdl:output>

				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">

				<soap:fault use="literal" name="fault" />
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="searchDuplicateCustomer">

			<soap:operation
				soapAction="http://services.apmoller.net/cmd/definitions/v2/searchDuplicateCustomer" />
			<wsdl:input>



				<soap:body use="literal" />
				<soap:header use="literal" message="tns:searchCustomerHeader"
					part="header" />
			</wsdl:input>
			<wsdl:output>

				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">

				<soap:fault use="literal" name="fault" />
			</wsdl:fault>
		</wsdl:operation>
		<wsdl:operation name="retrieveCustomer">

			<soap:operation
				soapAction="http://services.apmoller.net/cmd/definitions/v2/retrieveCustomer" />
			<wsdl:input>



				<soap:body use="literal" />
				<soap:header use="literal" message="tns:searchCustomerHeader"
					part="header" />
			</wsdl:input>
			<wsdl:output>

				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">

				<soap:fault use="literal" name="fault" />
			</wsdl:fault>
		</wsdl:operation>

		<wsdl:operation name="retrieveRelationships">

			<soap:operation
				soapAction="http://services.apmoller.net/cmd/definitions/v2/retrieveRelationships" />
			<wsdl:input>


				<soap:body use="literal" />
				<soap:header use="literal" message="tns:searchCustomerHeader"
					part="header" />
			</wsdl:input>
			<wsdl:output>

				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">

				<soap:fault use="literal" name="fault" />
			</wsdl:fault>
		</wsdl:operation>

		<wsdl:operation name="retrieveConcern">
			<soap:operation
				soapAction="http://services.apmoller.net/cmd/definitions/v2/retrieveConcern" />
			<wsdl:input>
				<soap:body use="literal" />
				<soap:header use="literal" message="tns:searchCustomerHeader"
					part="header" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="fault">
				<soap:fault use="literal" name="fault" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CustomerSearchService">
		<wsdl:port name="SearchCustomerPort" binding="tns:SearchCustomerBinding">
			<soap:address
				location="http://scrbipcdk001152:47801/CustomerSearch/v2/CustomerSearchService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
