/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.OpsFacility.smds.operations.MSK;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** OpsFacility Parent details */
@org.apache.avro.specific.AvroGenerated
public class OpsFacilityParentDetails extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6506683080015905714L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OpsFacilityParentDetails\",\"namespace\":\"com.maersk.OpsFacility.smds.operations.MSK\",\"doc\":\"OpsFacility Parent details\",\"fields\":[{\"name\":\"ParentRowID\",\"type\":[\"null\",\"string\"]},{\"name\":\"Name\",\"type\":[\"null\",\"string\"]},{\"name\":\"Type\",\"type\":[\"null\",\"string\"]},{\"name\":\"OpsFacilityParentAlternateCodeDetails\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OpsFacilityParentAlternateCode\",\"doc\":\"OpsFacility Parent AlternateCode details\",\"fields\":[{\"name\":\"CodeType\",\"type\":[\"null\",\"string\"]},{\"name\":\"Code\",\"type\":[\"null\",\"string\"]}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OpsFacilityParentDetails> ENCODER =
      new BinaryMessageEncoder<OpsFacilityParentDetails>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OpsFacilityParentDetails> DECODER =
      new BinaryMessageDecoder<OpsFacilityParentDetails>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OpsFacilityParentDetails> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OpsFacilityParentDetails> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OpsFacilityParentDetails>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OpsFacilityParentDetails to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OpsFacilityParentDetails from a ByteBuffer. */
  public static OpsFacilityParentDetails fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence ParentRowID;
  @Deprecated public java.lang.CharSequence Name;
  @Deprecated public java.lang.CharSequence Type;
  @Deprecated public java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentAlternateCode> OpsFacilityParentAlternateCodeDetails;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OpsFacilityParentDetails() {}

  /**
   * All-args constructor.
   * @param ParentRowID The new value for ParentRowID
   * @param Name The new value for Name
   * @param Type The new value for Type
   * @param OpsFacilityParentAlternateCodeDetails The new value for OpsFacilityParentAlternateCodeDetails
   */
  public OpsFacilityParentDetails(java.lang.CharSequence ParentRowID, java.lang.CharSequence Name, java.lang.CharSequence Type, java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentAlternateCode> OpsFacilityParentAlternateCodeDetails) {
    this.ParentRowID = ParentRowID;
    this.Name = Name;
    this.Type = Type;
    this.OpsFacilityParentAlternateCodeDetails = OpsFacilityParentAlternateCodeDetails;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ParentRowID;
    case 1: return Name;
    case 2: return Type;
    case 3: return OpsFacilityParentAlternateCodeDetails;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ParentRowID = (java.lang.CharSequence)value$; break;
    case 1: Name = (java.lang.CharSequence)value$; break;
    case 2: Type = (java.lang.CharSequence)value$; break;
    case 3: OpsFacilityParentAlternateCodeDetails = (java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentAlternateCode>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ParentRowID' field.
   * @return The value of the 'ParentRowID' field.
   */
  public java.lang.CharSequence getParentRowID() {
    return ParentRowID;
  }

  /**
   * Sets the value of the 'ParentRowID' field.
   * @param value the value to set.
   */
  public void setParentRowID(java.lang.CharSequence value) {
    this.ParentRowID = value;
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }

  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'Type' field.
   * @return The value of the 'Type' field.
   */
  public java.lang.CharSequence getType() {
    return Type;
  }

  /**
   * Sets the value of the 'Type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.Type = value;
  }

  /**
   * Gets the value of the 'OpsFacilityParentAlternateCodeDetails' field.
   * @return The value of the 'OpsFacilityParentAlternateCodeDetails' field.
   */
  public java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentAlternateCode> getOpsFacilityParentAlternateCodeDetails() {
    return OpsFacilityParentAlternateCodeDetails;
  }

  /**
   * Sets the value of the 'OpsFacilityParentAlternateCodeDetails' field.
   * @param value the value to set.
   */
  public void setOpsFacilityParentAlternateCodeDetails(java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentAlternateCode> value) {
    this.OpsFacilityParentAlternateCodeDetails = value;
  }

  /**
   * Creates a new OpsFacilityParentDetails RecordBuilder.
   * @return A new OpsFacilityParentDetails RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder newBuilder() {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder();
  }

  /**
   * Creates a new OpsFacilityParentDetails RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OpsFacilityParentDetails RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder(other);
  }

  /**
   * Creates a new OpsFacilityParentDetails RecordBuilder by copying an existing OpsFacilityParentDetails instance.
   * @param other The existing instance to copy.
   * @return A new OpsFacilityParentDetails RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder(other);
  }

  /**
   * RecordBuilder for OpsFacilityParentDetails instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OpsFacilityParentDetails>
    implements org.apache.avro.data.RecordBuilder<OpsFacilityParentDetails> {

    private java.lang.CharSequence ParentRowID;
    private java.lang.CharSequence Name;
    private java.lang.CharSequence Type;
    private java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentAlternateCode> OpsFacilityParentAlternateCodeDetails;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ParentRowID)) {
        this.ParentRowID = data().deepCopy(fields()[0].schema(), other.ParentRowID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Type)) {
        this.Type = data().deepCopy(fields()[2].schema(), other.Type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.OpsFacilityParentAlternateCodeDetails)) {
        this.OpsFacilityParentAlternateCodeDetails = data().deepCopy(fields()[3].schema(), other.OpsFacilityParentAlternateCodeDetails);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OpsFacilityParentDetails instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.ParentRowID)) {
        this.ParentRowID = data().deepCopy(fields()[0].schema(), other.ParentRowID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.Type)) {
        this.Type = data().deepCopy(fields()[2].schema(), other.Type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.OpsFacilityParentAlternateCodeDetails)) {
        this.OpsFacilityParentAlternateCodeDetails = data().deepCopy(fields()[3].schema(), other.OpsFacilityParentAlternateCodeDetails);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'ParentRowID' field.
      * @return The value.
      */
    public java.lang.CharSequence getParentRowID() {
      return ParentRowID;
    }

    /**
      * Sets the value of the 'ParentRowID' field.
      * @param value The value of 'ParentRowID'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder setParentRowID(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ParentRowID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ParentRowID' field has been set.
      * @return True if the 'ParentRowID' field has been set, false otherwise.
      */
    public boolean hasParentRowID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ParentRowID' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder clearParentRowID() {
      ParentRowID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }

    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder clearName() {
      Name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'Type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return Type;
    }

    /**
      * Sets the value of the 'Type' field.
      * @param value The value of 'Type'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder setType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.Type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'Type' field has been set.
      * @return True if the 'Type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'Type' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder clearType() {
      Type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'OpsFacilityParentAlternateCodeDetails' field.
      * @return The value.
      */
    public java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentAlternateCode> getOpsFacilityParentAlternateCodeDetails() {
      return OpsFacilityParentAlternateCodeDetails;
    }

    /**
      * Sets the value of the 'OpsFacilityParentAlternateCodeDetails' field.
      * @param value The value of 'OpsFacilityParentAlternateCodeDetails'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder setOpsFacilityParentAlternateCodeDetails(java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentAlternateCode> value) {
      validate(fields()[3], value);
      this.OpsFacilityParentAlternateCodeDetails = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'OpsFacilityParentAlternateCodeDetails' field has been set.
      * @return True if the 'OpsFacilityParentAlternateCodeDetails' field has been set, false otherwise.
      */
    public boolean hasOpsFacilityParentAlternateCodeDetails() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'OpsFacilityParentAlternateCodeDetails' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentDetails.Builder clearOpsFacilityParentAlternateCodeDetails() {
      OpsFacilityParentAlternateCodeDetails = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OpsFacilityParentDetails build() {
      try {
        OpsFacilityParentDetails record = new OpsFacilityParentDetails();
        record.ParentRowID = fieldSetFlags()[0] ? this.ParentRowID : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Name = fieldSetFlags()[1] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.Type = fieldSetFlags()[2] ? this.Type : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.OpsFacilityParentAlternateCodeDetails = fieldSetFlags()[3] ? this.OpsFacilityParentAlternateCodeDetails : (java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityParentAlternateCode>) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OpsFacilityParentDetails>
    WRITER$ = (org.apache.avro.io.DatumWriter<OpsFacilityParentDetails>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OpsFacilityParentDetails>
    READER$ = (org.apache.avro.io.DatumReader<OpsFacilityParentDetails>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
