/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.OpsFacility.smds.operations.MSK;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Ops Facility Details */
@org.apache.avro.specific.AvroGenerated
public class OpsFacilityDetail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6633162680567337209L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OpsFacilityDetail\",\"namespace\":\"com.maersk.OpsFacility.smds.operations.MSK\",\"doc\":\"Ops Facility Details\",\"fields\":[{\"name\":\"FctOpsRowid\",\"type\":[\"null\",\"string\"]},{\"name\":\"WeightLimitCraneKg\",\"type\":[\"null\",\"string\"]},{\"name\":\"WeightLimitYardKg\",\"type\":[\"null\",\"string\"]},{\"name\":\"VesselAgent\",\"type\":[\"null\",\"string\"]},{\"name\":\"GPSFlag\",\"type\":[\"null\",\"string\"]},{\"name\":\"GSMFlag\",\"type\":[\"null\",\"string\"]},{\"name\":\"OceanFreightPricing\",\"type\":[\"null\",\"string\"]},{\"name\":\"FacilityBrand\",\"type\":[\"null\",\"string\"]},{\"name\":\"FacilityType\",\"type\":[\"null\",\"string\"]},{\"name\":\"ExportEnquiriesEmail\",\"type\":[\"null\",\"string\"]},{\"name\":\"ImportEnquiriesEmail\",\"type\":[\"null\",\"string\"]},{\"name\":\"FacilityFunction\",\"type\":[\"null\",\"string\"]},{\"name\":\"FacilityFunctionDesc\",\"type\":[\"null\",\"string\"]},{\"name\":\"InternationalDialCode\",\"type\":[\"null\",\"string\"]},{\"name\":\"TelephoneNumber\",\"type\":[\"null\",\"string\"]},{\"name\":\"OpsFacilityType\",\"type\":[\"null\",{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OpsFacilityType\",\"doc\":\"Ops Facility Type\",\"fields\":[{\"name\":\"Code\",\"type\":[\"null\",\"string\"]},{\"name\":\"Name\",\"type\":[\"null\",\"string\"]},{\"name\":\"MasterType\",\"type\":[\"null\",\"string\"]},{\"name\":\"ValidThroughDate\",\"type\":[\"null\",\"string\"]}]}}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OpsFacilityDetail> ENCODER =
      new BinaryMessageEncoder<OpsFacilityDetail>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OpsFacilityDetail> DECODER =
      new BinaryMessageDecoder<OpsFacilityDetail>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OpsFacilityDetail> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OpsFacilityDetail> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OpsFacilityDetail>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OpsFacilityDetail to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OpsFacilityDetail from a ByteBuffer. */
  public static OpsFacilityDetail fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence FctOpsRowid;
  @Deprecated public java.lang.CharSequence WeightLimitCraneKg;
  @Deprecated public java.lang.CharSequence WeightLimitYardKg;
  @Deprecated public java.lang.CharSequence VesselAgent;
  @Deprecated public java.lang.CharSequence GPSFlag;
  @Deprecated public java.lang.CharSequence GSMFlag;
  @Deprecated public java.lang.CharSequence OceanFreightPricing;
  @Deprecated public java.lang.CharSequence FacilityBrand;
  @Deprecated public java.lang.CharSequence FacilityType;
  @Deprecated public java.lang.CharSequence ExportEnquiriesEmail;
  @Deprecated public java.lang.CharSequence ImportEnquiriesEmail;
  @Deprecated public java.lang.CharSequence FacilityFunction;
  @Deprecated public java.lang.CharSequence FacilityFunctionDesc;
  @Deprecated public java.lang.CharSequence InternationalDialCode;
  @Deprecated public java.lang.CharSequence TelephoneNumber;
  @Deprecated public java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType> OpsFacilityType;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OpsFacilityDetail() {}

  /**
   * All-args constructor.
   * @param FctOpsRowid The new value for FctOpsRowid
   * @param WeightLimitCraneKg The new value for WeightLimitCraneKg
   * @param WeightLimitYardKg The new value for WeightLimitYardKg
   * @param VesselAgent The new value for VesselAgent
   * @param GPSFlag The new value for GPSFlag
   * @param GSMFlag The new value for GSMFlag
   * @param OceanFreightPricing The new value for OceanFreightPricing
   * @param FacilityBrand The new value for FacilityBrand
   * @param FacilityType The new value for FacilityType
   * @param ExportEnquiriesEmail The new value for ExportEnquiriesEmail
   * @param ImportEnquiriesEmail The new value for ImportEnquiriesEmail
   * @param FacilityFunction The new value for FacilityFunction
   * @param FacilityFunctionDesc The new value for FacilityFunctionDesc
   * @param InternationalDialCode The new value for InternationalDialCode
   * @param TelephoneNumber The new value for TelephoneNumber
   * @param OpsFacilityType The new value for OpsFacilityType
   */
  public OpsFacilityDetail(java.lang.CharSequence FctOpsRowid, java.lang.CharSequence WeightLimitCraneKg, java.lang.CharSequence WeightLimitYardKg, java.lang.CharSequence VesselAgent, java.lang.CharSequence GPSFlag, java.lang.CharSequence GSMFlag, java.lang.CharSequence OceanFreightPricing, java.lang.CharSequence FacilityBrand, java.lang.CharSequence FacilityType, java.lang.CharSequence ExportEnquiriesEmail, java.lang.CharSequence ImportEnquiriesEmail, java.lang.CharSequence FacilityFunction, java.lang.CharSequence FacilityFunctionDesc, java.lang.CharSequence InternationalDialCode, java.lang.CharSequence TelephoneNumber, java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType> OpsFacilityType) {
    this.FctOpsRowid = FctOpsRowid;
    this.WeightLimitCraneKg = WeightLimitCraneKg;
    this.WeightLimitYardKg = WeightLimitYardKg;
    this.VesselAgent = VesselAgent;
    this.GPSFlag = GPSFlag;
    this.GSMFlag = GSMFlag;
    this.OceanFreightPricing = OceanFreightPricing;
    this.FacilityBrand = FacilityBrand;
    this.FacilityType = FacilityType;
    this.ExportEnquiriesEmail = ExportEnquiriesEmail;
    this.ImportEnquiriesEmail = ImportEnquiriesEmail;
    this.FacilityFunction = FacilityFunction;
    this.FacilityFunctionDesc = FacilityFunctionDesc;
    this.InternationalDialCode = InternationalDialCode;
    this.TelephoneNumber = TelephoneNumber;
    this.OpsFacilityType = OpsFacilityType;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return FctOpsRowid;
    case 1: return WeightLimitCraneKg;
    case 2: return WeightLimitYardKg;
    case 3: return VesselAgent;
    case 4: return GPSFlag;
    case 5: return GSMFlag;
    case 6: return OceanFreightPricing;
    case 7: return FacilityBrand;
    case 8: return FacilityType;
    case 9: return ExportEnquiriesEmail;
    case 10: return ImportEnquiriesEmail;
    case 11: return FacilityFunction;
    case 12: return FacilityFunctionDesc;
    case 13: return InternationalDialCode;
    case 14: return TelephoneNumber;
    case 15: return OpsFacilityType;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: FctOpsRowid = (java.lang.CharSequence)value$; break;
    case 1: WeightLimitCraneKg = (java.lang.CharSequence)value$; break;
    case 2: WeightLimitYardKg = (java.lang.CharSequence)value$; break;
    case 3: VesselAgent = (java.lang.CharSequence)value$; break;
    case 4: GPSFlag = (java.lang.CharSequence)value$; break;
    case 5: GSMFlag = (java.lang.CharSequence)value$; break;
    case 6: OceanFreightPricing = (java.lang.CharSequence)value$; break;
    case 7: FacilityBrand = (java.lang.CharSequence)value$; break;
    case 8: FacilityType = (java.lang.CharSequence)value$; break;
    case 9: ExportEnquiriesEmail = (java.lang.CharSequence)value$; break;
    case 10: ImportEnquiriesEmail = (java.lang.CharSequence)value$; break;
    case 11: FacilityFunction = (java.lang.CharSequence)value$; break;
    case 12: FacilityFunctionDesc = (java.lang.CharSequence)value$; break;
    case 13: InternationalDialCode = (java.lang.CharSequence)value$; break;
    case 14: TelephoneNumber = (java.lang.CharSequence)value$; break;
    case 15: OpsFacilityType = (java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'FctOpsRowid' field.
   * @return The value of the 'FctOpsRowid' field.
   */
  public java.lang.CharSequence getFctOpsRowid() {
    return FctOpsRowid;
  }

  /**
   * Sets the value of the 'FctOpsRowid' field.
   * @param value the value to set.
   */
  public void setFctOpsRowid(java.lang.CharSequence value) {
    this.FctOpsRowid = value;
  }

  /**
   * Gets the value of the 'WeightLimitCraneKg' field.
   * @return The value of the 'WeightLimitCraneKg' field.
   */
  public java.lang.CharSequence getWeightLimitCraneKg() {
    return WeightLimitCraneKg;
  }

  /**
   * Sets the value of the 'WeightLimitCraneKg' field.
   * @param value the value to set.
   */
  public void setWeightLimitCraneKg(java.lang.CharSequence value) {
    this.WeightLimitCraneKg = value;
  }

  /**
   * Gets the value of the 'WeightLimitYardKg' field.
   * @return The value of the 'WeightLimitYardKg' field.
   */
  public java.lang.CharSequence getWeightLimitYardKg() {
    return WeightLimitYardKg;
  }

  /**
   * Sets the value of the 'WeightLimitYardKg' field.
   * @param value the value to set.
   */
  public void setWeightLimitYardKg(java.lang.CharSequence value) {
    this.WeightLimitYardKg = value;
  }

  /**
   * Gets the value of the 'VesselAgent' field.
   * @return The value of the 'VesselAgent' field.
   */
  public java.lang.CharSequence getVesselAgent() {
    return VesselAgent;
  }

  /**
   * Sets the value of the 'VesselAgent' field.
   * @param value the value to set.
   */
  public void setVesselAgent(java.lang.CharSequence value) {
    this.VesselAgent = value;
  }

  /**
   * Gets the value of the 'GPSFlag' field.
   * @return The value of the 'GPSFlag' field.
   */
  public java.lang.CharSequence getGPSFlag() {
    return GPSFlag;
  }

  /**
   * Sets the value of the 'GPSFlag' field.
   * @param value the value to set.
   */
  public void setGPSFlag(java.lang.CharSequence value) {
    this.GPSFlag = value;
  }

  /**
   * Gets the value of the 'GSMFlag' field.
   * @return The value of the 'GSMFlag' field.
   */
  public java.lang.CharSequence getGSMFlag() {
    return GSMFlag;
  }

  /**
   * Sets the value of the 'GSMFlag' field.
   * @param value the value to set.
   */
  public void setGSMFlag(java.lang.CharSequence value) {
    this.GSMFlag = value;
  }

  /**
   * Gets the value of the 'OceanFreightPricing' field.
   * @return The value of the 'OceanFreightPricing' field.
   */
  public java.lang.CharSequence getOceanFreightPricing() {
    return OceanFreightPricing;
  }

  /**
   * Sets the value of the 'OceanFreightPricing' field.
   * @param value the value to set.
   */
  public void setOceanFreightPricing(java.lang.CharSequence value) {
    this.OceanFreightPricing = value;
  }

  /**
   * Gets the value of the 'FacilityBrand' field.
   * @return The value of the 'FacilityBrand' field.
   */
  public java.lang.CharSequence getFacilityBrand() {
    return FacilityBrand;
  }

  /**
   * Sets the value of the 'FacilityBrand' field.
   * @param value the value to set.
   */
  public void setFacilityBrand(java.lang.CharSequence value) {
    this.FacilityBrand = value;
  }

  /**
   * Gets the value of the 'FacilityType' field.
   * @return The value of the 'FacilityType' field.
   */
  public java.lang.CharSequence getFacilityType() {
    return FacilityType;
  }

  /**
   * Sets the value of the 'FacilityType' field.
   * @param value the value to set.
   */
  public void setFacilityType(java.lang.CharSequence value) {
    this.FacilityType = value;
  }

  /**
   * Gets the value of the 'ExportEnquiriesEmail' field.
   * @return The value of the 'ExportEnquiriesEmail' field.
   */
  public java.lang.CharSequence getExportEnquiriesEmail() {
    return ExportEnquiriesEmail;
  }

  /**
   * Sets the value of the 'ExportEnquiriesEmail' field.
   * @param value the value to set.
   */
  public void setExportEnquiriesEmail(java.lang.CharSequence value) {
    this.ExportEnquiriesEmail = value;
  }

  /**
   * Gets the value of the 'ImportEnquiriesEmail' field.
   * @return The value of the 'ImportEnquiriesEmail' field.
   */
  public java.lang.CharSequence getImportEnquiriesEmail() {
    return ImportEnquiriesEmail;
  }

  /**
   * Sets the value of the 'ImportEnquiriesEmail' field.
   * @param value the value to set.
   */
  public void setImportEnquiriesEmail(java.lang.CharSequence value) {
    this.ImportEnquiriesEmail = value;
  }

  /**
   * Gets the value of the 'FacilityFunction' field.
   * @return The value of the 'FacilityFunction' field.
   */
  public java.lang.CharSequence getFacilityFunction() {
    return FacilityFunction;
  }

  /**
   * Sets the value of the 'FacilityFunction' field.
   * @param value the value to set.
   */
  public void setFacilityFunction(java.lang.CharSequence value) {
    this.FacilityFunction = value;
  }

  /**
   * Gets the value of the 'FacilityFunctionDesc' field.
   * @return The value of the 'FacilityFunctionDesc' field.
   */
  public java.lang.CharSequence getFacilityFunctionDesc() {
    return FacilityFunctionDesc;
  }

  /**
   * Sets the value of the 'FacilityFunctionDesc' field.
   * @param value the value to set.
   */
  public void setFacilityFunctionDesc(java.lang.CharSequence value) {
    this.FacilityFunctionDesc = value;
  }

  /**
   * Gets the value of the 'InternationalDialCode' field.
   * @return The value of the 'InternationalDialCode' field.
   */
  public java.lang.CharSequence getInternationalDialCode() {
    return InternationalDialCode;
  }

  /**
   * Sets the value of the 'InternationalDialCode' field.
   * @param value the value to set.
   */
  public void setInternationalDialCode(java.lang.CharSequence value) {
    this.InternationalDialCode = value;
  }

  /**
   * Gets the value of the 'TelephoneNumber' field.
   * @return The value of the 'TelephoneNumber' field.
   */
  public java.lang.CharSequence getTelephoneNumber() {
    return TelephoneNumber;
  }

  /**
   * Sets the value of the 'TelephoneNumber' field.
   * @param value the value to set.
   */
  public void setTelephoneNumber(java.lang.CharSequence value) {
    this.TelephoneNumber = value;
  }

  /**
   * Gets the value of the 'OpsFacilityType' field.
   * @return The value of the 'OpsFacilityType' field.
   */
  public java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType> getOpsFacilityType() {
    return OpsFacilityType;
  }

  /**
   * Sets the value of the 'OpsFacilityType' field.
   * @param value the value to set.
   */
  public void setOpsFacilityType(java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType> value) {
    this.OpsFacilityType = value;
  }

  /**
   * Creates a new OpsFacilityDetail RecordBuilder.
   * @return A new OpsFacilityDetail RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder newBuilder() {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder();
  }

  /**
   * Creates a new OpsFacilityDetail RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OpsFacilityDetail RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder(other);
  }

  /**
   * Creates a new OpsFacilityDetail RecordBuilder by copying an existing OpsFacilityDetail instance.
   * @param other The existing instance to copy.
   * @return A new OpsFacilityDetail RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder(other);
  }

  /**
   * RecordBuilder for OpsFacilityDetail instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OpsFacilityDetail>
    implements org.apache.avro.data.RecordBuilder<OpsFacilityDetail> {

    private java.lang.CharSequence FctOpsRowid;
    private java.lang.CharSequence WeightLimitCraneKg;
    private java.lang.CharSequence WeightLimitYardKg;
    private java.lang.CharSequence VesselAgent;
    private java.lang.CharSequence GPSFlag;
    private java.lang.CharSequence GSMFlag;
    private java.lang.CharSequence OceanFreightPricing;
    private java.lang.CharSequence FacilityBrand;
    private java.lang.CharSequence FacilityType;
    private java.lang.CharSequence ExportEnquiriesEmail;
    private java.lang.CharSequence ImportEnquiriesEmail;
    private java.lang.CharSequence FacilityFunction;
    private java.lang.CharSequence FacilityFunctionDesc;
    private java.lang.CharSequence InternationalDialCode;
    private java.lang.CharSequence TelephoneNumber;
    private java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType> OpsFacilityType;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.FctOpsRowid)) {
        this.FctOpsRowid = data().deepCopy(fields()[0].schema(), other.FctOpsRowid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.WeightLimitCraneKg)) {
        this.WeightLimitCraneKg = data().deepCopy(fields()[1].schema(), other.WeightLimitCraneKg);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.WeightLimitYardKg)) {
        this.WeightLimitYardKg = data().deepCopy(fields()[2].schema(), other.WeightLimitYardKg);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.VesselAgent)) {
        this.VesselAgent = data().deepCopy(fields()[3].schema(), other.VesselAgent);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.GPSFlag)) {
        this.GPSFlag = data().deepCopy(fields()[4].schema(), other.GPSFlag);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.GSMFlag)) {
        this.GSMFlag = data().deepCopy(fields()[5].schema(), other.GSMFlag);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.OceanFreightPricing)) {
        this.OceanFreightPricing = data().deepCopy(fields()[6].schema(), other.OceanFreightPricing);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.FacilityBrand)) {
        this.FacilityBrand = data().deepCopy(fields()[7].schema(), other.FacilityBrand);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.FacilityType)) {
        this.FacilityType = data().deepCopy(fields()[8].schema(), other.FacilityType);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ExportEnquiriesEmail)) {
        this.ExportEnquiriesEmail = data().deepCopy(fields()[9].schema(), other.ExportEnquiriesEmail);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ImportEnquiriesEmail)) {
        this.ImportEnquiriesEmail = data().deepCopy(fields()[10].schema(), other.ImportEnquiriesEmail);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.FacilityFunction)) {
        this.FacilityFunction = data().deepCopy(fields()[11].schema(), other.FacilityFunction);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.FacilityFunctionDesc)) {
        this.FacilityFunctionDesc = data().deepCopy(fields()[12].schema(), other.FacilityFunctionDesc);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.InternationalDialCode)) {
        this.InternationalDialCode = data().deepCopy(fields()[13].schema(), other.InternationalDialCode);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.TelephoneNumber)) {
        this.TelephoneNumber = data().deepCopy(fields()[14].schema(), other.TelephoneNumber);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.OpsFacilityType)) {
        this.OpsFacilityType = data().deepCopy(fields()[15].schema(), other.OpsFacilityType);
        fieldSetFlags()[15] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OpsFacilityDetail instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.FctOpsRowid)) {
        this.FctOpsRowid = data().deepCopy(fields()[0].schema(), other.FctOpsRowid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.WeightLimitCraneKg)) {
        this.WeightLimitCraneKg = data().deepCopy(fields()[1].schema(), other.WeightLimitCraneKg);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.WeightLimitYardKg)) {
        this.WeightLimitYardKg = data().deepCopy(fields()[2].schema(), other.WeightLimitYardKg);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.VesselAgent)) {
        this.VesselAgent = data().deepCopy(fields()[3].schema(), other.VesselAgent);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.GPSFlag)) {
        this.GPSFlag = data().deepCopy(fields()[4].schema(), other.GPSFlag);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.GSMFlag)) {
        this.GSMFlag = data().deepCopy(fields()[5].schema(), other.GSMFlag);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.OceanFreightPricing)) {
        this.OceanFreightPricing = data().deepCopy(fields()[6].schema(), other.OceanFreightPricing);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.FacilityBrand)) {
        this.FacilityBrand = data().deepCopy(fields()[7].schema(), other.FacilityBrand);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.FacilityType)) {
        this.FacilityType = data().deepCopy(fields()[8].schema(), other.FacilityType);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.ExportEnquiriesEmail)) {
        this.ExportEnquiriesEmail = data().deepCopy(fields()[9].schema(), other.ExportEnquiriesEmail);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.ImportEnquiriesEmail)) {
        this.ImportEnquiriesEmail = data().deepCopy(fields()[10].schema(), other.ImportEnquiriesEmail);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.FacilityFunction)) {
        this.FacilityFunction = data().deepCopy(fields()[11].schema(), other.FacilityFunction);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.FacilityFunctionDesc)) {
        this.FacilityFunctionDesc = data().deepCopy(fields()[12].schema(), other.FacilityFunctionDesc);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.InternationalDialCode)) {
        this.InternationalDialCode = data().deepCopy(fields()[13].schema(), other.InternationalDialCode);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.TelephoneNumber)) {
        this.TelephoneNumber = data().deepCopy(fields()[14].schema(), other.TelephoneNumber);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.OpsFacilityType)) {
        this.OpsFacilityType = data().deepCopy(fields()[15].schema(), other.OpsFacilityType);
        fieldSetFlags()[15] = true;
      }
    }

    /**
      * Gets the value of the 'FctOpsRowid' field.
      * @return The value.
      */
    public java.lang.CharSequence getFctOpsRowid() {
      return FctOpsRowid;
    }

    /**
      * Sets the value of the 'FctOpsRowid' field.
      * @param value The value of 'FctOpsRowid'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setFctOpsRowid(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.FctOpsRowid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'FctOpsRowid' field has been set.
      * @return True if the 'FctOpsRowid' field has been set, false otherwise.
      */
    public boolean hasFctOpsRowid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'FctOpsRowid' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearFctOpsRowid() {
      FctOpsRowid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'WeightLimitCraneKg' field.
      * @return The value.
      */
    public java.lang.CharSequence getWeightLimitCraneKg() {
      return WeightLimitCraneKg;
    }

    /**
      * Sets the value of the 'WeightLimitCraneKg' field.
      * @param value The value of 'WeightLimitCraneKg'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setWeightLimitCraneKg(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.WeightLimitCraneKg = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'WeightLimitCraneKg' field has been set.
      * @return True if the 'WeightLimitCraneKg' field has been set, false otherwise.
      */
    public boolean hasWeightLimitCraneKg() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'WeightLimitCraneKg' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearWeightLimitCraneKg() {
      WeightLimitCraneKg = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'WeightLimitYardKg' field.
      * @return The value.
      */
    public java.lang.CharSequence getWeightLimitYardKg() {
      return WeightLimitYardKg;
    }

    /**
      * Sets the value of the 'WeightLimitYardKg' field.
      * @param value The value of 'WeightLimitYardKg'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setWeightLimitYardKg(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.WeightLimitYardKg = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'WeightLimitYardKg' field has been set.
      * @return True if the 'WeightLimitYardKg' field has been set, false otherwise.
      */
    public boolean hasWeightLimitYardKg() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'WeightLimitYardKg' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearWeightLimitYardKg() {
      WeightLimitYardKg = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'VesselAgent' field.
      * @return The value.
      */
    public java.lang.CharSequence getVesselAgent() {
      return VesselAgent;
    }

    /**
      * Sets the value of the 'VesselAgent' field.
      * @param value The value of 'VesselAgent'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setVesselAgent(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.VesselAgent = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'VesselAgent' field has been set.
      * @return True if the 'VesselAgent' field has been set, false otherwise.
      */
    public boolean hasVesselAgent() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'VesselAgent' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearVesselAgent() {
      VesselAgent = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'GPSFlag' field.
      * @return The value.
      */
    public java.lang.CharSequence getGPSFlag() {
      return GPSFlag;
    }

    /**
      * Sets the value of the 'GPSFlag' field.
      * @param value The value of 'GPSFlag'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setGPSFlag(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.GPSFlag = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'GPSFlag' field has been set.
      * @return True if the 'GPSFlag' field has been set, false otherwise.
      */
    public boolean hasGPSFlag() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'GPSFlag' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearGPSFlag() {
      GPSFlag = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'GSMFlag' field.
      * @return The value.
      */
    public java.lang.CharSequence getGSMFlag() {
      return GSMFlag;
    }

    /**
      * Sets the value of the 'GSMFlag' field.
      * @param value The value of 'GSMFlag'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setGSMFlag(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.GSMFlag = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'GSMFlag' field has been set.
      * @return True if the 'GSMFlag' field has been set, false otherwise.
      */
    public boolean hasGSMFlag() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'GSMFlag' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearGSMFlag() {
      GSMFlag = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'OceanFreightPricing' field.
      * @return The value.
      */
    public java.lang.CharSequence getOceanFreightPricing() {
      return OceanFreightPricing;
    }

    /**
      * Sets the value of the 'OceanFreightPricing' field.
      * @param value The value of 'OceanFreightPricing'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setOceanFreightPricing(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.OceanFreightPricing = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'OceanFreightPricing' field has been set.
      * @return True if the 'OceanFreightPricing' field has been set, false otherwise.
      */
    public boolean hasOceanFreightPricing() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'OceanFreightPricing' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearOceanFreightPricing() {
      OceanFreightPricing = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'FacilityBrand' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityBrand() {
      return FacilityBrand;
    }

    /**
      * Sets the value of the 'FacilityBrand' field.
      * @param value The value of 'FacilityBrand'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setFacilityBrand(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.FacilityBrand = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'FacilityBrand' field has been set.
      * @return True if the 'FacilityBrand' field has been set, false otherwise.
      */
    public boolean hasFacilityBrand() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'FacilityBrand' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearFacilityBrand() {
      FacilityBrand = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'FacilityType' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityType() {
      return FacilityType;
    }

    /**
      * Sets the value of the 'FacilityType' field.
      * @param value The value of 'FacilityType'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setFacilityType(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.FacilityType = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'FacilityType' field has been set.
      * @return True if the 'FacilityType' field has been set, false otherwise.
      */
    public boolean hasFacilityType() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'FacilityType' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearFacilityType() {
      FacilityType = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'ExportEnquiriesEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getExportEnquiriesEmail() {
      return ExportEnquiriesEmail;
    }

    /**
      * Sets the value of the 'ExportEnquiriesEmail' field.
      * @param value The value of 'ExportEnquiriesEmail'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setExportEnquiriesEmail(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.ExportEnquiriesEmail = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'ExportEnquiriesEmail' field has been set.
      * @return True if the 'ExportEnquiriesEmail' field has been set, false otherwise.
      */
    public boolean hasExportEnquiriesEmail() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'ExportEnquiriesEmail' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearExportEnquiriesEmail() {
      ExportEnquiriesEmail = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'ImportEnquiriesEmail' field.
      * @return The value.
      */
    public java.lang.CharSequence getImportEnquiriesEmail() {
      return ImportEnquiriesEmail;
    }

    /**
      * Sets the value of the 'ImportEnquiriesEmail' field.
      * @param value The value of 'ImportEnquiriesEmail'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setImportEnquiriesEmail(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.ImportEnquiriesEmail = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'ImportEnquiriesEmail' field has been set.
      * @return True if the 'ImportEnquiriesEmail' field has been set, false otherwise.
      */
    public boolean hasImportEnquiriesEmail() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'ImportEnquiriesEmail' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearImportEnquiriesEmail() {
      ImportEnquiriesEmail = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'FacilityFunction' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityFunction() {
      return FacilityFunction;
    }

    /**
      * Sets the value of the 'FacilityFunction' field.
      * @param value The value of 'FacilityFunction'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setFacilityFunction(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.FacilityFunction = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'FacilityFunction' field has been set.
      * @return True if the 'FacilityFunction' field has been set, false otherwise.
      */
    public boolean hasFacilityFunction() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'FacilityFunction' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearFacilityFunction() {
      FacilityFunction = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'FacilityFunctionDesc' field.
      * @return The value.
      */
    public java.lang.CharSequence getFacilityFunctionDesc() {
      return FacilityFunctionDesc;
    }

    /**
      * Sets the value of the 'FacilityFunctionDesc' field.
      * @param value The value of 'FacilityFunctionDesc'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setFacilityFunctionDesc(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.FacilityFunctionDesc = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'FacilityFunctionDesc' field has been set.
      * @return True if the 'FacilityFunctionDesc' field has been set, false otherwise.
      */
    public boolean hasFacilityFunctionDesc() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'FacilityFunctionDesc' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearFacilityFunctionDesc() {
      FacilityFunctionDesc = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'InternationalDialCode' field.
      * @return The value.
      */
    public java.lang.CharSequence getInternationalDialCode() {
      return InternationalDialCode;
    }

    /**
      * Sets the value of the 'InternationalDialCode' field.
      * @param value The value of 'InternationalDialCode'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setInternationalDialCode(java.lang.CharSequence value) {
      validate(fields()[13], value);
      this.InternationalDialCode = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'InternationalDialCode' field has been set.
      * @return True if the 'InternationalDialCode' field has been set, false otherwise.
      */
    public boolean hasInternationalDialCode() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'InternationalDialCode' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearInternationalDialCode() {
      InternationalDialCode = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'TelephoneNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getTelephoneNumber() {
      return TelephoneNumber;
    }

    /**
      * Sets the value of the 'TelephoneNumber' field.
      * @param value The value of 'TelephoneNumber'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setTelephoneNumber(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.TelephoneNumber = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'TelephoneNumber' field has been set.
      * @return True if the 'TelephoneNumber' field has been set, false otherwise.
      */
    public boolean hasTelephoneNumber() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'TelephoneNumber' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearTelephoneNumber() {
      TelephoneNumber = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'OpsFacilityType' field.
      * @return The value.
      */
    public java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType> getOpsFacilityType() {
      return OpsFacilityType;
    }

    /**
      * Sets the value of the 'OpsFacilityType' field.
      * @param value The value of 'OpsFacilityType'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder setOpsFacilityType(java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType> value) {
      validate(fields()[15], value);
      this.OpsFacilityType = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'OpsFacilityType' field has been set.
      * @return True if the 'OpsFacilityType' field has been set, false otherwise.
      */
    public boolean hasOpsFacilityType() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'OpsFacilityType' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityDetail.Builder clearOpsFacilityType() {
      OpsFacilityType = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OpsFacilityDetail build() {
      try {
        OpsFacilityDetail record = new OpsFacilityDetail();
        record.FctOpsRowid = fieldSetFlags()[0] ? this.FctOpsRowid : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.WeightLimitCraneKg = fieldSetFlags()[1] ? this.WeightLimitCraneKg : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.WeightLimitYardKg = fieldSetFlags()[2] ? this.WeightLimitYardKg : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.VesselAgent = fieldSetFlags()[3] ? this.VesselAgent : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.GPSFlag = fieldSetFlags()[4] ? this.GPSFlag : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.GSMFlag = fieldSetFlags()[5] ? this.GSMFlag : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.OceanFreightPricing = fieldSetFlags()[6] ? this.OceanFreightPricing : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.FacilityBrand = fieldSetFlags()[7] ? this.FacilityBrand : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.FacilityType = fieldSetFlags()[8] ? this.FacilityType : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.ExportEnquiriesEmail = fieldSetFlags()[9] ? this.ExportEnquiriesEmail : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.ImportEnquiriesEmail = fieldSetFlags()[10] ? this.ImportEnquiriesEmail : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.FacilityFunction = fieldSetFlags()[11] ? this.FacilityFunction : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.FacilityFunctionDesc = fieldSetFlags()[12] ? this.FacilityFunctionDesc : (java.lang.CharSequence) defaultValue(fields()[12]);
        record.InternationalDialCode = fieldSetFlags()[13] ? this.InternationalDialCode : (java.lang.CharSequence) defaultValue(fields()[13]);
        record.TelephoneNumber = fieldSetFlags()[14] ? this.TelephoneNumber : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.OpsFacilityType = fieldSetFlags()[15] ? this.OpsFacilityType : (java.util.List<com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType>) defaultValue(fields()[15]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OpsFacilityDetail>
    WRITER$ = (org.apache.avro.io.DatumWriter<OpsFacilityDetail>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OpsFacilityDetail>
    READER$ = (org.apache.avro.io.DatumReader<OpsFacilityDetail>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
