/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.OpsFacility.smds.operations.MSK;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Ops Facility ContactDetail details */
@org.apache.avro.specific.AvroGenerated
public class OpsFacilityContactDetail extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7620952472688547984L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OpsFacilityContactDetail\",\"namespace\":\"com.maersk.OpsFacility.smds.operations.MSK\",\"doc\":\"Ops Facility ContactDetail details\",\"fields\":[{\"name\":\"FirstName\",\"type\":[\"null\",\"string\"]},{\"name\":\"LastName\",\"type\":[\"null\",\"string\"]},{\"name\":\"JobTitle\",\"type\":[\"null\",\"string\"]},{\"name\":\"Department\",\"type\":[\"null\",\"string\"]},{\"name\":\"InternationalDialingCdPhone\",\"type\":[\"null\",\"string\"]},{\"name\":\"Extension\",\"type\":[\"null\",\"string\"]},{\"name\":\"PhoneNumber\",\"type\":[\"null\",\"string\"]},{\"name\":\"InternationalDialingCdMobile\",\"type\":[\"null\",\"string\"]},{\"name\":\"MobileNumber\",\"type\":[\"null\",\"string\"]},{\"name\":\"InternaltionalDialingCodeFax\",\"type\":[\"null\",\"string\"]},{\"name\":\"FaxNumber\",\"type\":[\"null\",\"string\"]},{\"name\":\"EmailAddress\",\"type\":[\"null\",\"string\"]},{\"name\":\"ValidThroughDate\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OpsFacilityContactDetail> ENCODER =
      new BinaryMessageEncoder<OpsFacilityContactDetail>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OpsFacilityContactDetail> DECODER =
      new BinaryMessageDecoder<OpsFacilityContactDetail>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OpsFacilityContactDetail> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OpsFacilityContactDetail> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OpsFacilityContactDetail>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OpsFacilityContactDetail to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OpsFacilityContactDetail from a ByteBuffer. */
  public static OpsFacilityContactDetail fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence FirstName;
  @Deprecated public java.lang.CharSequence LastName;
  @Deprecated public java.lang.CharSequence JobTitle;
  @Deprecated public java.lang.CharSequence Department;
  @Deprecated public java.lang.CharSequence InternationalDialingCdPhone;
  @Deprecated public java.lang.CharSequence Extension;
  @Deprecated public java.lang.CharSequence PhoneNumber;
  @Deprecated public java.lang.CharSequence InternationalDialingCdMobile;
  @Deprecated public java.lang.CharSequence MobileNumber;
  @Deprecated public java.lang.CharSequence InternaltionalDialingCodeFax;
  @Deprecated public java.lang.CharSequence FaxNumber;
  @Deprecated public java.lang.CharSequence EmailAddress;
  @Deprecated public java.lang.CharSequence ValidThroughDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OpsFacilityContactDetail() {}

  /**
   * All-args constructor.
   * @param FirstName The new value for FirstName
   * @param LastName The new value for LastName
   * @param JobTitle The new value for JobTitle
   * @param Department The new value for Department
   * @param InternationalDialingCdPhone The new value for InternationalDialingCdPhone
   * @param Extension The new value for Extension
   * @param PhoneNumber The new value for PhoneNumber
   * @param InternationalDialingCdMobile The new value for InternationalDialingCdMobile
   * @param MobileNumber The new value for MobileNumber
   * @param InternaltionalDialingCodeFax The new value for InternaltionalDialingCodeFax
   * @param FaxNumber The new value for FaxNumber
   * @param EmailAddress The new value for EmailAddress
   * @param ValidThroughDate The new value for ValidThroughDate
   */
  public OpsFacilityContactDetail(java.lang.CharSequence FirstName, java.lang.CharSequence LastName, java.lang.CharSequence JobTitle, java.lang.CharSequence Department, java.lang.CharSequence InternationalDialingCdPhone, java.lang.CharSequence Extension, java.lang.CharSequence PhoneNumber, java.lang.CharSequence InternationalDialingCdMobile, java.lang.CharSequence MobileNumber, java.lang.CharSequence InternaltionalDialingCodeFax, java.lang.CharSequence FaxNumber, java.lang.CharSequence EmailAddress, java.lang.CharSequence ValidThroughDate) {
    this.FirstName = FirstName;
    this.LastName = LastName;
    this.JobTitle = JobTitle;
    this.Department = Department;
    this.InternationalDialingCdPhone = InternationalDialingCdPhone;
    this.Extension = Extension;
    this.PhoneNumber = PhoneNumber;
    this.InternationalDialingCdMobile = InternationalDialingCdMobile;
    this.MobileNumber = MobileNumber;
    this.InternaltionalDialingCodeFax = InternaltionalDialingCodeFax;
    this.FaxNumber = FaxNumber;
    this.EmailAddress = EmailAddress;
    this.ValidThroughDate = ValidThroughDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return FirstName;
    case 1: return LastName;
    case 2: return JobTitle;
    case 3: return Department;
    case 4: return InternationalDialingCdPhone;
    case 5: return Extension;
    case 6: return PhoneNumber;
    case 7: return InternationalDialingCdMobile;
    case 8: return MobileNumber;
    case 9: return InternaltionalDialingCodeFax;
    case 10: return FaxNumber;
    case 11: return EmailAddress;
    case 12: return ValidThroughDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: FirstName = (java.lang.CharSequence)value$; break;
    case 1: LastName = (java.lang.CharSequence)value$; break;
    case 2: JobTitle = (java.lang.CharSequence)value$; break;
    case 3: Department = (java.lang.CharSequence)value$; break;
    case 4: InternationalDialingCdPhone = (java.lang.CharSequence)value$; break;
    case 5: Extension = (java.lang.CharSequence)value$; break;
    case 6: PhoneNumber = (java.lang.CharSequence)value$; break;
    case 7: InternationalDialingCdMobile = (java.lang.CharSequence)value$; break;
    case 8: MobileNumber = (java.lang.CharSequence)value$; break;
    case 9: InternaltionalDialingCodeFax = (java.lang.CharSequence)value$; break;
    case 10: FaxNumber = (java.lang.CharSequence)value$; break;
    case 11: EmailAddress = (java.lang.CharSequence)value$; break;
    case 12: ValidThroughDate = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'FirstName' field.
   * @return The value of the 'FirstName' field.
   */
  public java.lang.CharSequence getFirstName() {
    return FirstName;
  }

  /**
   * Sets the value of the 'FirstName' field.
   * @param value the value to set.
   */
  public void setFirstName(java.lang.CharSequence value) {
    this.FirstName = value;
  }

  /**
   * Gets the value of the 'LastName' field.
   * @return The value of the 'LastName' field.
   */
  public java.lang.CharSequence getLastName() {
    return LastName;
  }

  /**
   * Sets the value of the 'LastName' field.
   * @param value the value to set.
   */
  public void setLastName(java.lang.CharSequence value) {
    this.LastName = value;
  }

  /**
   * Gets the value of the 'JobTitle' field.
   * @return The value of the 'JobTitle' field.
   */
  public java.lang.CharSequence getJobTitle() {
    return JobTitle;
  }

  /**
   * Sets the value of the 'JobTitle' field.
   * @param value the value to set.
   */
  public void setJobTitle(java.lang.CharSequence value) {
    this.JobTitle = value;
  }

  /**
   * Gets the value of the 'Department' field.
   * @return The value of the 'Department' field.
   */
  public java.lang.CharSequence getDepartment() {
    return Department;
  }

  /**
   * Sets the value of the 'Department' field.
   * @param value the value to set.
   */
  public void setDepartment(java.lang.CharSequence value) {
    this.Department = value;
  }

  /**
   * Gets the value of the 'InternationalDialingCdPhone' field.
   * @return The value of the 'InternationalDialingCdPhone' field.
   */
  public java.lang.CharSequence getInternationalDialingCdPhone() {
    return InternationalDialingCdPhone;
  }

  /**
   * Sets the value of the 'InternationalDialingCdPhone' field.
   * @param value the value to set.
   */
  public void setInternationalDialingCdPhone(java.lang.CharSequence value) {
    this.InternationalDialingCdPhone = value;
  }

  /**
   * Gets the value of the 'Extension' field.
   * @return The value of the 'Extension' field.
   */
  public java.lang.CharSequence getExtension() {
    return Extension;
  }

  /**
   * Sets the value of the 'Extension' field.
   * @param value the value to set.
   */
  public void setExtension(java.lang.CharSequence value) {
    this.Extension = value;
  }

  /**
   * Gets the value of the 'PhoneNumber' field.
   * @return The value of the 'PhoneNumber' field.
   */
  public java.lang.CharSequence getPhoneNumber() {
    return PhoneNumber;
  }

  /**
   * Sets the value of the 'PhoneNumber' field.
   * @param value the value to set.
   */
  public void setPhoneNumber(java.lang.CharSequence value) {
    this.PhoneNumber = value;
  }

  /**
   * Gets the value of the 'InternationalDialingCdMobile' field.
   * @return The value of the 'InternationalDialingCdMobile' field.
   */
  public java.lang.CharSequence getInternationalDialingCdMobile() {
    return InternationalDialingCdMobile;
  }

  /**
   * Sets the value of the 'InternationalDialingCdMobile' field.
   * @param value the value to set.
   */
  public void setInternationalDialingCdMobile(java.lang.CharSequence value) {
    this.InternationalDialingCdMobile = value;
  }

  /**
   * Gets the value of the 'MobileNumber' field.
   * @return The value of the 'MobileNumber' field.
   */
  public java.lang.CharSequence getMobileNumber() {
    return MobileNumber;
  }

  /**
   * Sets the value of the 'MobileNumber' field.
   * @param value the value to set.
   */
  public void setMobileNumber(java.lang.CharSequence value) {
    this.MobileNumber = value;
  }

  /**
   * Gets the value of the 'InternaltionalDialingCodeFax' field.
   * @return The value of the 'InternaltionalDialingCodeFax' field.
   */
  public java.lang.CharSequence getInternaltionalDialingCodeFax() {
    return InternaltionalDialingCodeFax;
  }

  /**
   * Sets the value of the 'InternaltionalDialingCodeFax' field.
   * @param value the value to set.
   */
  public void setInternaltionalDialingCodeFax(java.lang.CharSequence value) {
    this.InternaltionalDialingCodeFax = value;
  }

  /**
   * Gets the value of the 'FaxNumber' field.
   * @return The value of the 'FaxNumber' field.
   */
  public java.lang.CharSequence getFaxNumber() {
    return FaxNumber;
  }

  /**
   * Sets the value of the 'FaxNumber' field.
   * @param value the value to set.
   */
  public void setFaxNumber(java.lang.CharSequence value) {
    this.FaxNumber = value;
  }

  /**
   * Gets the value of the 'EmailAddress' field.
   * @return The value of the 'EmailAddress' field.
   */
  public java.lang.CharSequence getEmailAddress() {
    return EmailAddress;
  }

  /**
   * Sets the value of the 'EmailAddress' field.
   * @param value the value to set.
   */
  public void setEmailAddress(java.lang.CharSequence value) {
    this.EmailAddress = value;
  }

  /**
   * Gets the value of the 'ValidThroughDate' field.
   * @return The value of the 'ValidThroughDate' field.
   */
  public java.lang.CharSequence getValidThroughDate() {
    return ValidThroughDate;
  }

  /**
   * Sets the value of the 'ValidThroughDate' field.
   * @param value the value to set.
   */
  public void setValidThroughDate(java.lang.CharSequence value) {
    this.ValidThroughDate = value;
  }

  /**
   * Creates a new OpsFacilityContactDetail RecordBuilder.
   * @return A new OpsFacilityContactDetail RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder newBuilder() {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder();
  }

  /**
   * Creates a new OpsFacilityContactDetail RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OpsFacilityContactDetail RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder(other);
  }

  /**
   * Creates a new OpsFacilityContactDetail RecordBuilder by copying an existing OpsFacilityContactDetail instance.
   * @param other The existing instance to copy.
   * @return A new OpsFacilityContactDetail RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder(other);
  }

  /**
   * RecordBuilder for OpsFacilityContactDetail instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OpsFacilityContactDetail>
    implements org.apache.avro.data.RecordBuilder<OpsFacilityContactDetail> {

    private java.lang.CharSequence FirstName;
    private java.lang.CharSequence LastName;
    private java.lang.CharSequence JobTitle;
    private java.lang.CharSequence Department;
    private java.lang.CharSequence InternationalDialingCdPhone;
    private java.lang.CharSequence Extension;
    private java.lang.CharSequence PhoneNumber;
    private java.lang.CharSequence InternationalDialingCdMobile;
    private java.lang.CharSequence MobileNumber;
    private java.lang.CharSequence InternaltionalDialingCodeFax;
    private java.lang.CharSequence FaxNumber;
    private java.lang.CharSequence EmailAddress;
    private java.lang.CharSequence ValidThroughDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.FirstName)) {
        this.FirstName = data().deepCopy(fields()[0].schema(), other.FirstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.LastName)) {
        this.LastName = data().deepCopy(fields()[1].schema(), other.LastName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.JobTitle)) {
        this.JobTitle = data().deepCopy(fields()[2].schema(), other.JobTitle);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Department)) {
        this.Department = data().deepCopy(fields()[3].schema(), other.Department);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.InternationalDialingCdPhone)) {
        this.InternationalDialingCdPhone = data().deepCopy(fields()[4].schema(), other.InternationalDialingCdPhone);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.Extension)) {
        this.Extension = data().deepCopy(fields()[5].schema(), other.Extension);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.PhoneNumber)) {
        this.PhoneNumber = data().deepCopy(fields()[6].schema(), other.PhoneNumber);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.InternationalDialingCdMobile)) {
        this.InternationalDialingCdMobile = data().deepCopy(fields()[7].schema(), other.InternationalDialingCdMobile);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.MobileNumber)) {
        this.MobileNumber = data().deepCopy(fields()[8].schema(), other.MobileNumber);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.InternaltionalDialingCodeFax)) {
        this.InternaltionalDialingCodeFax = data().deepCopy(fields()[9].schema(), other.InternaltionalDialingCodeFax);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.FaxNumber)) {
        this.FaxNumber = data().deepCopy(fields()[10].schema(), other.FaxNumber);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.EmailAddress)) {
        this.EmailAddress = data().deepCopy(fields()[11].schema(), other.EmailAddress);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ValidThroughDate)) {
        this.ValidThroughDate = data().deepCopy(fields()[12].schema(), other.ValidThroughDate);
        fieldSetFlags()[12] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OpsFacilityContactDetail instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.FirstName)) {
        this.FirstName = data().deepCopy(fields()[0].schema(), other.FirstName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.LastName)) {
        this.LastName = data().deepCopy(fields()[1].schema(), other.LastName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.JobTitle)) {
        this.JobTitle = data().deepCopy(fields()[2].schema(), other.JobTitle);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.Department)) {
        this.Department = data().deepCopy(fields()[3].schema(), other.Department);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.InternationalDialingCdPhone)) {
        this.InternationalDialingCdPhone = data().deepCopy(fields()[4].schema(), other.InternationalDialingCdPhone);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.Extension)) {
        this.Extension = data().deepCopy(fields()[5].schema(), other.Extension);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.PhoneNumber)) {
        this.PhoneNumber = data().deepCopy(fields()[6].schema(), other.PhoneNumber);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.InternationalDialingCdMobile)) {
        this.InternationalDialingCdMobile = data().deepCopy(fields()[7].schema(), other.InternationalDialingCdMobile);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.MobileNumber)) {
        this.MobileNumber = data().deepCopy(fields()[8].schema(), other.MobileNumber);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.InternaltionalDialingCodeFax)) {
        this.InternaltionalDialingCodeFax = data().deepCopy(fields()[9].schema(), other.InternaltionalDialingCodeFax);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.FaxNumber)) {
        this.FaxNumber = data().deepCopy(fields()[10].schema(), other.FaxNumber);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.EmailAddress)) {
        this.EmailAddress = data().deepCopy(fields()[11].schema(), other.EmailAddress);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.ValidThroughDate)) {
        this.ValidThroughDate = data().deepCopy(fields()[12].schema(), other.ValidThroughDate);
        fieldSetFlags()[12] = true;
      }
    }

    /**
      * Gets the value of the 'FirstName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFirstName() {
      return FirstName;
    }

    /**
      * Sets the value of the 'FirstName' field.
      * @param value The value of 'FirstName'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setFirstName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.FirstName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'FirstName' field has been set.
      * @return True if the 'FirstName' field has been set, false otherwise.
      */
    public boolean hasFirstName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'FirstName' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearFirstName() {
      FirstName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'LastName' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastName() {
      return LastName;
    }

    /**
      * Sets the value of the 'LastName' field.
      * @param value The value of 'LastName'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setLastName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.LastName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'LastName' field has been set.
      * @return True if the 'LastName' field has been set, false otherwise.
      */
    public boolean hasLastName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'LastName' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearLastName() {
      LastName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'JobTitle' field.
      * @return The value.
      */
    public java.lang.CharSequence getJobTitle() {
      return JobTitle;
    }

    /**
      * Sets the value of the 'JobTitle' field.
      * @param value The value of 'JobTitle'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setJobTitle(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.JobTitle = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'JobTitle' field has been set.
      * @return True if the 'JobTitle' field has been set, false otherwise.
      */
    public boolean hasJobTitle() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'JobTitle' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearJobTitle() {
      JobTitle = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'Department' field.
      * @return The value.
      */
    public java.lang.CharSequence getDepartment() {
      return Department;
    }

    /**
      * Sets the value of the 'Department' field.
      * @param value The value of 'Department'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setDepartment(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.Department = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'Department' field has been set.
      * @return True if the 'Department' field has been set, false otherwise.
      */
    public boolean hasDepartment() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'Department' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearDepartment() {
      Department = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'InternationalDialingCdPhone' field.
      * @return The value.
      */
    public java.lang.CharSequence getInternationalDialingCdPhone() {
      return InternationalDialingCdPhone;
    }

    /**
      * Sets the value of the 'InternationalDialingCdPhone' field.
      * @param value The value of 'InternationalDialingCdPhone'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setInternationalDialingCdPhone(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.InternationalDialingCdPhone = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'InternationalDialingCdPhone' field has been set.
      * @return True if the 'InternationalDialingCdPhone' field has been set, false otherwise.
      */
    public boolean hasInternationalDialingCdPhone() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'InternationalDialingCdPhone' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearInternationalDialingCdPhone() {
      InternationalDialingCdPhone = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'Extension' field.
      * @return The value.
      */
    public java.lang.CharSequence getExtension() {
      return Extension;
    }

    /**
      * Sets the value of the 'Extension' field.
      * @param value The value of 'Extension'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setExtension(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.Extension = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'Extension' field has been set.
      * @return True if the 'Extension' field has been set, false otherwise.
      */
    public boolean hasExtension() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'Extension' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearExtension() {
      Extension = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'PhoneNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getPhoneNumber() {
      return PhoneNumber;
    }

    /**
      * Sets the value of the 'PhoneNumber' field.
      * @param value The value of 'PhoneNumber'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setPhoneNumber(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.PhoneNumber = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'PhoneNumber' field has been set.
      * @return True if the 'PhoneNumber' field has been set, false otherwise.
      */
    public boolean hasPhoneNumber() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'PhoneNumber' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearPhoneNumber() {
      PhoneNumber = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'InternationalDialingCdMobile' field.
      * @return The value.
      */
    public java.lang.CharSequence getInternationalDialingCdMobile() {
      return InternationalDialingCdMobile;
    }

    /**
      * Sets the value of the 'InternationalDialingCdMobile' field.
      * @param value The value of 'InternationalDialingCdMobile'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setInternationalDialingCdMobile(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.InternationalDialingCdMobile = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'InternationalDialingCdMobile' field has been set.
      * @return True if the 'InternationalDialingCdMobile' field has been set, false otherwise.
      */
    public boolean hasInternationalDialingCdMobile() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'InternationalDialingCdMobile' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearInternationalDialingCdMobile() {
      InternationalDialingCdMobile = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'MobileNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getMobileNumber() {
      return MobileNumber;
    }

    /**
      * Sets the value of the 'MobileNumber' field.
      * @param value The value of 'MobileNumber'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setMobileNumber(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.MobileNumber = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'MobileNumber' field has been set.
      * @return True if the 'MobileNumber' field has been set, false otherwise.
      */
    public boolean hasMobileNumber() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'MobileNumber' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearMobileNumber() {
      MobileNumber = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'InternaltionalDialingCodeFax' field.
      * @return The value.
      */
    public java.lang.CharSequence getInternaltionalDialingCodeFax() {
      return InternaltionalDialingCodeFax;
    }

    /**
      * Sets the value of the 'InternaltionalDialingCodeFax' field.
      * @param value The value of 'InternaltionalDialingCodeFax'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setInternaltionalDialingCodeFax(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.InternaltionalDialingCodeFax = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'InternaltionalDialingCodeFax' field has been set.
      * @return True if the 'InternaltionalDialingCodeFax' field has been set, false otherwise.
      */
    public boolean hasInternaltionalDialingCodeFax() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'InternaltionalDialingCodeFax' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearInternaltionalDialingCodeFax() {
      InternaltionalDialingCodeFax = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'FaxNumber' field.
      * @return The value.
      */
    public java.lang.CharSequence getFaxNumber() {
      return FaxNumber;
    }

    /**
      * Sets the value of the 'FaxNumber' field.
      * @param value The value of 'FaxNumber'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setFaxNumber(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.FaxNumber = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'FaxNumber' field has been set.
      * @return True if the 'FaxNumber' field has been set, false otherwise.
      */
    public boolean hasFaxNumber() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'FaxNumber' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearFaxNumber() {
      FaxNumber = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'EmailAddress' field.
      * @return The value.
      */
    public java.lang.CharSequence getEmailAddress() {
      return EmailAddress;
    }

    /**
      * Sets the value of the 'EmailAddress' field.
      * @param value The value of 'EmailAddress'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setEmailAddress(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.EmailAddress = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'EmailAddress' field has been set.
      * @return True if the 'EmailAddress' field has been set, false otherwise.
      */
    public boolean hasEmailAddress() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'EmailAddress' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearEmailAddress() {
      EmailAddress = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'ValidThroughDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getValidThroughDate() {
      return ValidThroughDate;
    }

    /**
      * Sets the value of the 'ValidThroughDate' field.
      * @param value The value of 'ValidThroughDate'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder setValidThroughDate(java.lang.CharSequence value) {
      validate(fields()[12], value);
      this.ValidThroughDate = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'ValidThroughDate' field has been set.
      * @return True if the 'ValidThroughDate' field has been set, false otherwise.
      */
    public boolean hasValidThroughDate() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'ValidThroughDate' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityContactDetail.Builder clearValidThroughDate() {
      ValidThroughDate = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OpsFacilityContactDetail build() {
      try {
        OpsFacilityContactDetail record = new OpsFacilityContactDetail();
        record.FirstName = fieldSetFlags()[0] ? this.FirstName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.LastName = fieldSetFlags()[1] ? this.LastName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.JobTitle = fieldSetFlags()[2] ? this.JobTitle : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.Department = fieldSetFlags()[3] ? this.Department : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.InternationalDialingCdPhone = fieldSetFlags()[4] ? this.InternationalDialingCdPhone : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.Extension = fieldSetFlags()[5] ? this.Extension : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.PhoneNumber = fieldSetFlags()[6] ? this.PhoneNumber : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.InternationalDialingCdMobile = fieldSetFlags()[7] ? this.InternationalDialingCdMobile : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.MobileNumber = fieldSetFlags()[8] ? this.MobileNumber : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.InternaltionalDialingCodeFax = fieldSetFlags()[9] ? this.InternaltionalDialingCodeFax : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.FaxNumber = fieldSetFlags()[10] ? this.FaxNumber : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.EmailAddress = fieldSetFlags()[11] ? this.EmailAddress : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.ValidThroughDate = fieldSetFlags()[12] ? this.ValidThroughDate : (java.lang.CharSequence) defaultValue(fields()[12]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OpsFacilityContactDetail>
    WRITER$ = (org.apache.avro.io.DatumWriter<OpsFacilityContactDetail>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OpsFacilityContactDetail>
    READER$ = (org.apache.avro.io.DatumReader<OpsFacilityContactDetail>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
