/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.OpsFacility.smds.operations.MSK;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Ops Facility Type */
@org.apache.avro.specific.AvroGenerated
public class OpsFacilityType extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -3516223053829933124L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OpsFacilityType\",\"namespace\":\"com.maersk.OpsFacility.smds.operations.MSK\",\"doc\":\"Ops Facility Type\",\"fields\":[{\"name\":\"Code\",\"type\":[\"null\",\"string\"]},{\"name\":\"Name\",\"type\":[\"null\",\"string\"]},{\"name\":\"MasterType\",\"type\":[\"null\",\"string\"]},{\"name\":\"ValidThroughDate\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OpsFacilityType> ENCODER =
      new BinaryMessageEncoder<OpsFacilityType>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OpsFacilityType> DECODER =
      new BinaryMessageDecoder<OpsFacilityType>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OpsFacilityType> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OpsFacilityType> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OpsFacilityType>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OpsFacilityType to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OpsFacilityType from a ByteBuffer. */
  public static OpsFacilityType fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Code;
  @Deprecated public java.lang.CharSequence Name;
  @Deprecated public java.lang.CharSequence MasterType;
  @Deprecated public java.lang.CharSequence ValidThroughDate;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OpsFacilityType() {}

  /**
   * All-args constructor.
   * @param Code The new value for Code
   * @param Name The new value for Name
   * @param MasterType The new value for MasterType
   * @param ValidThroughDate The new value for ValidThroughDate
   */
  public OpsFacilityType(java.lang.CharSequence Code, java.lang.CharSequence Name, java.lang.CharSequence MasterType, java.lang.CharSequence ValidThroughDate) {
    this.Code = Code;
    this.Name = Name;
    this.MasterType = MasterType;
    this.ValidThroughDate = ValidThroughDate;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Code;
    case 1: return Name;
    case 2: return MasterType;
    case 3: return ValidThroughDate;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Code = (java.lang.CharSequence)value$; break;
    case 1: Name = (java.lang.CharSequence)value$; break;
    case 2: MasterType = (java.lang.CharSequence)value$; break;
    case 3: ValidThroughDate = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Code' field.
   * @return The value of the 'Code' field.
   */
  public java.lang.CharSequence getCode() {
    return Code;
  }

  /**
   * Sets the value of the 'Code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.CharSequence value) {
    this.Code = value;
  }

  /**
   * Gets the value of the 'Name' field.
   * @return The value of the 'Name' field.
   */
  public java.lang.CharSequence getName() {
    return Name;
  }

  /**
   * Sets the value of the 'Name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.Name = value;
  }

  /**
   * Gets the value of the 'MasterType' field.
   * @return The value of the 'MasterType' field.
   */
  public java.lang.CharSequence getMasterType() {
    return MasterType;
  }

  /**
   * Sets the value of the 'MasterType' field.
   * @param value the value to set.
   */
  public void setMasterType(java.lang.CharSequence value) {
    this.MasterType = value;
  }

  /**
   * Gets the value of the 'ValidThroughDate' field.
   * @return The value of the 'ValidThroughDate' field.
   */
  public java.lang.CharSequence getValidThroughDate() {
    return ValidThroughDate;
  }

  /**
   * Sets the value of the 'ValidThroughDate' field.
   * @param value the value to set.
   */
  public void setValidThroughDate(java.lang.CharSequence value) {
    this.ValidThroughDate = value;
  }

  /**
   * Creates a new OpsFacilityType RecordBuilder.
   * @return A new OpsFacilityType RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder newBuilder() {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder();
  }

  /**
   * Creates a new OpsFacilityType RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OpsFacilityType RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder(other);
  }

  /**
   * Creates a new OpsFacilityType RecordBuilder by copying an existing OpsFacilityType instance.
   * @param other The existing instance to copy.
   * @return A new OpsFacilityType RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder(other);
  }

  /**
   * RecordBuilder for OpsFacilityType instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OpsFacilityType>
    implements org.apache.avro.data.RecordBuilder<OpsFacilityType> {

    private java.lang.CharSequence Code;
    private java.lang.CharSequence Name;
    private java.lang.CharSequence MasterType;
    private java.lang.CharSequence ValidThroughDate;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Code)) {
        this.Code = data().deepCopy(fields()[0].schema(), other.Code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MasterType)) {
        this.MasterType = data().deepCopy(fields()[2].schema(), other.MasterType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ValidThroughDate)) {
        this.ValidThroughDate = data().deepCopy(fields()[3].schema(), other.ValidThroughDate);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OpsFacilityType instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Code)) {
        this.Code = data().deepCopy(fields()[0].schema(), other.Code);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Name)) {
        this.Name = data().deepCopy(fields()[1].schema(), other.Name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.MasterType)) {
        this.MasterType = data().deepCopy(fields()[2].schema(), other.MasterType);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.ValidThroughDate)) {
        this.ValidThroughDate = data().deepCopy(fields()[3].schema(), other.ValidThroughDate);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'Code' field.
      * @return The value.
      */
    public java.lang.CharSequence getCode() {
      return Code;
    }

    /**
      * Sets the value of the 'Code' field.
      * @param value The value of 'Code'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder setCode(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Code = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Code' field has been set.
      * @return True if the 'Code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Code' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder clearCode() {
      Code = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return Name;
    }

    /**
      * Sets the value of the 'Name' field.
      * @param value The value of 'Name'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Name' field has been set.
      * @return True if the 'Name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Name' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder clearName() {
      Name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'MasterType' field.
      * @return The value.
      */
    public java.lang.CharSequence getMasterType() {
      return MasterType;
    }

    /**
      * Sets the value of the 'MasterType' field.
      * @param value The value of 'MasterType'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder setMasterType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.MasterType = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'MasterType' field has been set.
      * @return True if the 'MasterType' field has been set, false otherwise.
      */
    public boolean hasMasterType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'MasterType' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder clearMasterType() {
      MasterType = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'ValidThroughDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getValidThroughDate() {
      return ValidThroughDate;
    }

    /**
      * Sets the value of the 'ValidThroughDate' field.
      * @param value The value of 'ValidThroughDate'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder setValidThroughDate(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.ValidThroughDate = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'ValidThroughDate' field has been set.
      * @return True if the 'ValidThroughDate' field has been set, false otherwise.
      */
    public boolean hasValidThroughDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'ValidThroughDate' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityType.Builder clearValidThroughDate() {
      ValidThroughDate = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OpsFacilityType build() {
      try {
        OpsFacilityType record = new OpsFacilityType();
        record.Code = fieldSetFlags()[0] ? this.Code : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.Name = fieldSetFlags()[1] ? this.Name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.MasterType = fieldSetFlags()[2] ? this.MasterType : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.ValidThroughDate = fieldSetFlags()[3] ? this.ValidThroughDate : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OpsFacilityType>
    WRITER$ = (org.apache.avro.io.DatumWriter<OpsFacilityType>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OpsFacilityType>
    READER$ = (org.apache.avro.io.DatumReader<OpsFacilityType>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
