/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.maersk.OpsFacility.smds.operations.MSK;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Ops Facility OpeningHours details */
@org.apache.avro.specific.AvroGenerated
public class OpsFacilityOpeningHours extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5633182852934940414L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OpsFacilityOpeningHours\",\"namespace\":\"com.maersk.OpsFacility.smds.operations.MSK\",\"doc\":\"Ops Facility OpeningHours details\",\"fields\":[{\"name\":\"Day\",\"type\":[\"null\",\"string\"]},{\"name\":\"OpenTimeHours\",\"type\":[\"null\",\"string\"]},{\"name\":\"OpenTimeMinutes\",\"type\":[\"null\",\"string\"]},{\"name\":\"CloseTimeHours\",\"type\":[\"null\",\"string\"]},{\"name\":\"CloseTimeMinutes\",\"type\":[\"null\",\"string\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OpsFacilityOpeningHours> ENCODER =
      new BinaryMessageEncoder<OpsFacilityOpeningHours>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OpsFacilityOpeningHours> DECODER =
      new BinaryMessageDecoder<OpsFacilityOpeningHours>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OpsFacilityOpeningHours> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OpsFacilityOpeningHours> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OpsFacilityOpeningHours>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OpsFacilityOpeningHours to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OpsFacilityOpeningHours from a ByteBuffer. */
  public static OpsFacilityOpeningHours fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence Day;
  @Deprecated public java.lang.CharSequence OpenTimeHours;
  @Deprecated public java.lang.CharSequence OpenTimeMinutes;
  @Deprecated public java.lang.CharSequence CloseTimeHours;
  @Deprecated public java.lang.CharSequence CloseTimeMinutes;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OpsFacilityOpeningHours() {}

  /**
   * All-args constructor.
   * @param Day The new value for Day
   * @param OpenTimeHours The new value for OpenTimeHours
   * @param OpenTimeMinutes The new value for OpenTimeMinutes
   * @param CloseTimeHours The new value for CloseTimeHours
   * @param CloseTimeMinutes The new value for CloseTimeMinutes
   */
  public OpsFacilityOpeningHours(java.lang.CharSequence Day, java.lang.CharSequence OpenTimeHours, java.lang.CharSequence OpenTimeMinutes, java.lang.CharSequence CloseTimeHours, java.lang.CharSequence CloseTimeMinutes) {
    this.Day = Day;
    this.OpenTimeHours = OpenTimeHours;
    this.OpenTimeMinutes = OpenTimeMinutes;
    this.CloseTimeHours = CloseTimeHours;
    this.CloseTimeMinutes = CloseTimeMinutes;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return Day;
    case 1: return OpenTimeHours;
    case 2: return OpenTimeMinutes;
    case 3: return CloseTimeHours;
    case 4: return CloseTimeMinutes;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: Day = (java.lang.CharSequence)value$; break;
    case 1: OpenTimeHours = (java.lang.CharSequence)value$; break;
    case 2: OpenTimeMinutes = (java.lang.CharSequence)value$; break;
    case 3: CloseTimeHours = (java.lang.CharSequence)value$; break;
    case 4: CloseTimeMinutes = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'Day' field.
   * @return The value of the 'Day' field.
   */
  public java.lang.CharSequence getDay() {
    return Day;
  }

  /**
   * Sets the value of the 'Day' field.
   * @param value the value to set.
   */
  public void setDay(java.lang.CharSequence value) {
    this.Day = value;
  }

  /**
   * Gets the value of the 'OpenTimeHours' field.
   * @return The value of the 'OpenTimeHours' field.
   */
  public java.lang.CharSequence getOpenTimeHours() {
    return OpenTimeHours;
  }

  /**
   * Sets the value of the 'OpenTimeHours' field.
   * @param value the value to set.
   */
  public void setOpenTimeHours(java.lang.CharSequence value) {
    this.OpenTimeHours = value;
  }

  /**
   * Gets the value of the 'OpenTimeMinutes' field.
   * @return The value of the 'OpenTimeMinutes' field.
   */
  public java.lang.CharSequence getOpenTimeMinutes() {
    return OpenTimeMinutes;
  }

  /**
   * Sets the value of the 'OpenTimeMinutes' field.
   * @param value the value to set.
   */
  public void setOpenTimeMinutes(java.lang.CharSequence value) {
    this.OpenTimeMinutes = value;
  }

  /**
   * Gets the value of the 'CloseTimeHours' field.
   * @return The value of the 'CloseTimeHours' field.
   */
  public java.lang.CharSequence getCloseTimeHours() {
    return CloseTimeHours;
  }

  /**
   * Sets the value of the 'CloseTimeHours' field.
   * @param value the value to set.
   */
  public void setCloseTimeHours(java.lang.CharSequence value) {
    this.CloseTimeHours = value;
  }

  /**
   * Gets the value of the 'CloseTimeMinutes' field.
   * @return The value of the 'CloseTimeMinutes' field.
   */
  public java.lang.CharSequence getCloseTimeMinutes() {
    return CloseTimeMinutes;
  }

  /**
   * Sets the value of the 'CloseTimeMinutes' field.
   * @param value the value to set.
   */
  public void setCloseTimeMinutes(java.lang.CharSequence value) {
    this.CloseTimeMinutes = value;
  }

  /**
   * Creates a new OpsFacilityOpeningHours RecordBuilder.
   * @return A new OpsFacilityOpeningHours RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder newBuilder() {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder();
  }

  /**
   * Creates a new OpsFacilityOpeningHours RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OpsFacilityOpeningHours RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder(other);
  }

  /**
   * Creates a new OpsFacilityOpeningHours RecordBuilder by copying an existing OpsFacilityOpeningHours instance.
   * @param other The existing instance to copy.
   * @return A new OpsFacilityOpeningHours RecordBuilder
   */
  public static com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder newBuilder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours other) {
    return new com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder(other);
  }

  /**
   * RecordBuilder for OpsFacilityOpeningHours instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OpsFacilityOpeningHours>
    implements org.apache.avro.data.RecordBuilder<OpsFacilityOpeningHours> {

    private java.lang.CharSequence Day;
    private java.lang.CharSequence OpenTimeHours;
    private java.lang.CharSequence OpenTimeMinutes;
    private java.lang.CharSequence CloseTimeHours;
    private java.lang.CharSequence CloseTimeMinutes;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.Day)) {
        this.Day = data().deepCopy(fields()[0].schema(), other.Day);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.OpenTimeHours)) {
        this.OpenTimeHours = data().deepCopy(fields()[1].schema(), other.OpenTimeHours);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.OpenTimeMinutes)) {
        this.OpenTimeMinutes = data().deepCopy(fields()[2].schema(), other.OpenTimeMinutes);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CloseTimeHours)) {
        this.CloseTimeHours = data().deepCopy(fields()[3].schema(), other.CloseTimeHours);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CloseTimeMinutes)) {
        this.CloseTimeMinutes = data().deepCopy(fields()[4].schema(), other.CloseTimeMinutes);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OpsFacilityOpeningHours instance
     * @param other The existing instance to copy.
     */
    private Builder(com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.Day)) {
        this.Day = data().deepCopy(fields()[0].schema(), other.Day);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.OpenTimeHours)) {
        this.OpenTimeHours = data().deepCopy(fields()[1].schema(), other.OpenTimeHours);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.OpenTimeMinutes)) {
        this.OpenTimeMinutes = data().deepCopy(fields()[2].schema(), other.OpenTimeMinutes);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.CloseTimeHours)) {
        this.CloseTimeHours = data().deepCopy(fields()[3].schema(), other.CloseTimeHours);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.CloseTimeMinutes)) {
        this.CloseTimeMinutes = data().deepCopy(fields()[4].schema(), other.CloseTimeMinutes);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'Day' field.
      * @return The value.
      */
    public java.lang.CharSequence getDay() {
      return Day;
    }

    /**
      * Sets the value of the 'Day' field.
      * @param value The value of 'Day'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder setDay(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.Day = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'Day' field has been set.
      * @return True if the 'Day' field has been set, false otherwise.
      */
    public boolean hasDay() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'Day' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder clearDay() {
      Day = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'OpenTimeHours' field.
      * @return The value.
      */
    public java.lang.CharSequence getOpenTimeHours() {
      return OpenTimeHours;
    }

    /**
      * Sets the value of the 'OpenTimeHours' field.
      * @param value The value of 'OpenTimeHours'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder setOpenTimeHours(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.OpenTimeHours = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'OpenTimeHours' field has been set.
      * @return True if the 'OpenTimeHours' field has been set, false otherwise.
      */
    public boolean hasOpenTimeHours() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'OpenTimeHours' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder clearOpenTimeHours() {
      OpenTimeHours = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'OpenTimeMinutes' field.
      * @return The value.
      */
    public java.lang.CharSequence getOpenTimeMinutes() {
      return OpenTimeMinutes;
    }

    /**
      * Sets the value of the 'OpenTimeMinutes' field.
      * @param value The value of 'OpenTimeMinutes'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder setOpenTimeMinutes(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.OpenTimeMinutes = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'OpenTimeMinutes' field has been set.
      * @return True if the 'OpenTimeMinutes' field has been set, false otherwise.
      */
    public boolean hasOpenTimeMinutes() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'OpenTimeMinutes' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder clearOpenTimeMinutes() {
      OpenTimeMinutes = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'CloseTimeHours' field.
      * @return The value.
      */
    public java.lang.CharSequence getCloseTimeHours() {
      return CloseTimeHours;
    }

    /**
      * Sets the value of the 'CloseTimeHours' field.
      * @param value The value of 'CloseTimeHours'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder setCloseTimeHours(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.CloseTimeHours = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'CloseTimeHours' field has been set.
      * @return True if the 'CloseTimeHours' field has been set, false otherwise.
      */
    public boolean hasCloseTimeHours() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'CloseTimeHours' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder clearCloseTimeHours() {
      CloseTimeHours = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'CloseTimeMinutes' field.
      * @return The value.
      */
    public java.lang.CharSequence getCloseTimeMinutes() {
      return CloseTimeMinutes;
    }

    /**
      * Sets the value of the 'CloseTimeMinutes' field.
      * @param value The value of 'CloseTimeMinutes'.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder setCloseTimeMinutes(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.CloseTimeMinutes = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'CloseTimeMinutes' field has been set.
      * @return True if the 'CloseTimeMinutes' field has been set, false otherwise.
      */
    public boolean hasCloseTimeMinutes() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'CloseTimeMinutes' field.
      * @return This builder.
      */
    public com.maersk.OpsFacility.smds.operations.MSK.OpsFacilityOpeningHours.Builder clearCloseTimeMinutes() {
      CloseTimeMinutes = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OpsFacilityOpeningHours build() {
      try {
        OpsFacilityOpeningHours record = new OpsFacilityOpeningHours();
        record.Day = fieldSetFlags()[0] ? this.Day : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.OpenTimeHours = fieldSetFlags()[1] ? this.OpenTimeHours : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.OpenTimeMinutes = fieldSetFlags()[2] ? this.OpenTimeMinutes : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.CloseTimeHours = fieldSetFlags()[3] ? this.CloseTimeHours : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.CloseTimeMinutes = fieldSetFlags()[4] ? this.CloseTimeMinutes : (java.lang.CharSequence) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OpsFacilityOpeningHours>
    WRITER$ = (org.apache.avro.io.DatumWriter<OpsFacilityOpeningHours>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OpsFacilityOpeningHours>
    READER$ = (org.apache.avro.io.DatumReader<OpsFacilityOpeningHours>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
